const $=s=>document.querySelector(s),app=$('#app');
const V=id=>{const e=document.getElementById(id);return e?e.value:''};
const F=(id,l,v='',t='number')=>`<label>${l}</label><input id="${id}" type="${t}" inputmode="${t=='number'?'decimal':'text'}" step="any" value="${v}">`;
const R=(l,v,c='')=>`<div class="row"><span>${l}</span><b class="${c}">${v}</b></div>`;
const AVISO='<div class="card warn"><b>ATENÇÃO AO RISCO</b><p class="mut">Conteúdo educacional; nenhuma estratégia garante lucro. Alavancagem aumenta exposição e perdas podem ser rápidas. Stop não elimina todos os riscos. Liquidação pode ocorrer. Taxas, funding e slippage reduzem o resultado. Resultados passados não garantem resultados futuros.</p></div>';
document.documentElement.dataset.theme=S.cfg.theme;
const prog=()=>{const m=MODULOS.filter((_,i)=>modFrac([i])==1).length,q=Object.keys(S.quiz).length,c=Object.values(S.check).filter(x=>x===true).length;return{m,q,c,qp:Math.round(Object.values(S.quiz).filter(x=>x).length/QUIZ.length*100)}};
const bar=p=>`<div class="bar"><i style="width:${p}%"></i></div>`;
const stats=()=>{const t=S.trades,n=t.length,w=t.filter(x=>x.net>0),l=t.filter(x=>x.net<0),sum=k=>t.reduce((a,x)=>a+(x[k]||0),0);
 let sw=0,sl=0,mw=0,ml=0;t.forEach(x=>{if(x.net>0){sw++;sl=0}else if(x.net<0){sl++;sw=0}mw=Math.max(mw,sw);ml=Math.max(ml,sl)});
 const grp=k=>{const o={};t.forEach(x=>o[x[k]||'—']=(o[x[k]||'—']||0)+(x.net||0));return o};
 return{n,w:w.length,l:l.length,rate:n?w.length/n*100:NaN,bruto:sum('bruto'),taxas:sum('taxas'),fund:sum('fund'),net:sum('net'),max:Math.max(0,...t.map(x=>x.net||0)),min:Math.min(0,...t.map(x=>x.net||0)),mg:w.length?w.reduce((a,x)=>a+x.net,0)/w.length:0,mp:l.length?l.reduce((a,x)=>a+x.net,0)/l.length:0,mw,ml,ativo:grp('ativo'),tf:grp('tf'),side:grp('side')}};
const grpHTML=o=>Object.entries(o).map(([k,v])=>R(k,money(v),cls(v))).join('')||'<p class="mut">Sem dados.</p>';

const views={
inicio(){if(!S.welcomed)return`<div class="card"><h2>Bem-vindo ao Futures Trader Academy</h2><p>Aprenda primeiro. Simule depois. Registre suas operações. Só então considere operar com dinheiro real.</p><button class="btn" onclick="S.welcomed=true;save();go('aprender')">Começar aprendizado</button></div>`+AVISO;
 const p=prog(),s=stats(),u=S.trades[S.trades.length-1];
 return`<h2>Central de Trading</h2><div class="card"><b>Seu progresso</b>${bar(p.m/MODULOS.length*100)}<p class="mut">Módulos: ${p.m}/${MODULOS.length} · Checklist: ${p.c}/${CHECK.length} · Quiz: ${p.qp}% · Simulações: ${S.sims} · Operações: ${s.n}</p></div>
 <div class="grid"><div class="card"><span class="mut">Resultado do diário</span><div class="kpi ${cls(s.net)}">${money(s.net)}</div></div><div class="card"><span class="mut">Taxa de acerto</span><div class="kpi">${pct(s.rate)}</div></div></div>
 <div class="card"><span class="mut">Última operação</span><div>${u?`${u.data||''} · ${u.ativo||''} ${u.side||''} · <b class="${cls(u.net)}">${money(u.net)}</b>`:'Nenhuma registrada'}</div></div>
 <a class="btn" href="#aprender">Começar estudo</a><a class="btn alt" href="#analisar">Checklist de operação</a><a class="btn alt" href="#calc">Calculadoras</a><a class="btn alt" href="#diario">Diário de operações</a>`+AVISO},
aprender(a){if(a){const i=+a,m=MODULOS[i];return`<a href="#aprender">← Módulos</a><h2>${m.t}</h2>${m.b.map(x=>`<div class="card">${x}</div>`).join('')}<button class="btn ${S.done[i]?'ok':''}" onclick="S.done[${i}]=!S.done[${i}];if(!S.done[${i}])delete S.done[${i}];save();render()">${S.done[i]?'✓ Concluído':'Marcar como concluído'}</button>`+AVISO}
 return`<h2>Aprender</h2>${MODULOS.map((m,i)=>`<a class="card" style="display:block;text-decoration:none;color:inherit" href="#aprender/${i}"><b>${S.done[i]?'✅':'▫️'} ${m.t}</b></a>`).join('')}<a class="btn alt" href="#quiz">Fazer quiz (${prog().qp}%)</a>`},
quiz(a){const i=+a||0;if(i>=QUIZ.length)return`<div class="card"><h2>Quiz concluído</h2><p>Acertos: ${prog().qp}%</p><button class="btn" onclick="S.quiz={};save();go('quiz/0')">Refazer</button></div>`;
 const q=QUIZ[i];return`<h2>Quiz ${i+1}/${QUIZ.length}</h2>${bar(i/QUIZ.length*100)}<div class="card"><b>${q[0]}</b>${q[1].map((o,k)=>`<button class="btn alt opt" onclick="ans(${i},${k})">${o}</button>`).join('')}<div id="fb"></div></div>`},
analisar(a){const t=`<div class="tabs"><a class="btn ${!a?'':'alt'}" href="#analisar">Checklist</a><a class="btn ${a=='tec'?'':'alt'}" href="#analisar/tec">Análise técnica</a><a class="btn ${a=='sim'?'':'alt'}" href="#analisar/sim">Simulador</a></div>`;
 if(a=='tec')return t+`<div class="card"><h3>Análise técnica</h3><p>Monte sua própria leitura: contexto (tendência), estrutura (suporte, resistência, topos, fundos), confirmação (médias, volume, RSI, MACD) e cenário. Indicadores nem sempre concordam e não precisam estar todos ativos.</p><p class="mut">Cenários possíveis: alta, baixa ou espera. Nunca são certeza.</p><a class="btn" href="#aprender">Revisar módulos</a></div>`;
 if(a=='sim')return t+`<div class="card"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b>${F('s_b','Banca fictícia',1000)}<label>Long/Short</label><select id="s_s"><option value="long">Long</option><option value="short">Short</option></select>${F('s_e','Entrada',100)}${F('s_x','Saída',105)}${F('s_l','Alavancagem',10)}${F('s_st','Stop Loss (opcional)')}${F('s_tp','Take Profit (opcional)')}${F('s_m','Margem usada',100)}<button class="btn" onclick="sim()">Simular</button><div id="s_o"></div></div>`;
 const c=S.check,val=k=>c[k]||'';
 return t+`<div class="card"><h3>Checklist pré-operação</h3>${F('c_ativo','1. Ativo',val('ativo'),'text')}${F('c_tf','Timeframe principal',val('tf'),'text')}<label>Tendência</label><select id="c_tr">${['Alta','Baixa','Lateral'].map(x=>`<option ${val('tr')==x?'selected':''}>${x}</option>`).join('')}</select>
 <p class="mut">2–3. Estrutura e indicadores</p>${CHECK.map((x,i)=>`<label style="color:var(--tx)"><input type="checkbox" style="width:auto;min-height:0" ${c['k'+i]?'checked':''} onchange="S.check.k${i}=this.checked;save()"> ${x}</label>`).join('')}
 <label>4. Hipótese</label><select id="c_h">${['LONG','SHORT','NÃO OPERAR'].map(x=>`<option ${val('h')==x?'selected':''}>${x}</option>`).join('')}</select><label>Justificativa</label><textarea id="c_j">${val('j')}</textarea>
 ${F('c_e','5. Preço de entrada',val('e'))}${F('c_s','6. Preço do stop',val('s'))}${F('c_p','Valor máximo que aceita perder',val('p'))}${F('c_t','7. Preço alvo',val('t'))}<button class="btn alt" onclick="chk()">Calcular e concluir</button><div id="c_o"></div></div>`},
calc(a){const t=`<div class="tabs">${[['','Futuros'],['alav','Alavancagem'],['risco','Risco'],['cambio','USD⇄BRL'],['mais','Mais']].map(([k,n])=>`<a class="btn ${a==k||(!a&&!k)?'':'alt'}" href="#calc${k?'/'+k:''}">${n}</a>`).join('')}</div>`;
 const ipt=(ids)=>`oninput="${ids}()"`;
 if(a=='alav')return t+`<div class="card"><b>Calculadora de alavancagem</b>${F('a_m','Margem',20).replace('<input','<input oninput="calcA()"')}${F('a_l','Alavancagem (x)',10).replace('<input','<input oninput="calcA()"')}<div id="a_o"></div><p class="mut">Aproximação antes de taxas, funding e slippage. 10x não significa ganhar 10 vezes o dinheiro.</p></div>`;
 if(a=='risco')return t+`<div class="card"><b>Risco e tamanho da posição</b>${['r_b|Banca|'+(S.bank.cur||1000),'r_r|Risco máximo (%)|'+(S.bank.risco||1),'r_e|Entrada|100','r_s|Stop Loss|98','r_l|Alavancagem|5'].map(x=>{const[i,l,v]=x.split('|');return F(i,l,v).replace('<input','<input oninput="calcR()"')}).join('')}<div id="r_o"></div></div>`;
 if(a=='cambio')return t+`<div class="card"><b>Conversor</b>${F('f_v','Valor',20).replace('<input','<input oninput="calcF()"')}${F('f_c','Cotação usada (R$ por US$)',S.cfg.fx).replace('<input','<input oninput="calcF()"')}<label>Direção</label><select id="f_d" onchange="calcF()"><option value="u">USD → BRL</option><option value="b">BRL → USD</option></select><div id="f_o"></div></div>`;
 return t+`<div class="card"><b>Calculadora de Futuros (modelo genérico)</b>${F('k_a','Ativo','BTCUSDT','text')}<label>Long/Short</label><select id="k_s" onchange="calcK()"><option value="long">Long</option><option value="short">Short</option></select>${[['k_m','Margem',20],['k_l','Alavancagem',10],['k_e','Preço de entrada',100],['k_x','Preço de saída',105],['k_sl','Stop Loss',''],['k_tp','Take Profit',''],['k_fe','Taxa de entrada (%)',0.05],['k_fs','Taxa de saída (%)',0.05],['k_fu','Funding (%)',0]].map(([i,l,v])=>F(i,l,v).replace('<input','<input oninput="calcK()"')).join('')}<div id="k_o"></div><p class="mut">ESTIMATIVA EDUCACIONAL. O preço real de liquidação depende da corretora, contrato, margem, modo de margem, taxas, funding e regras específicas da plataforma.</p></div>`},
diario(a){const s=stats();const fld=[['d_data','Data',new Date().toISOString().slice(0,10),'date'],['d_hora','Hora',new Date().toTimeString().slice(0,5),'time'],['d_ativo','Ativo','','text'],['d_tf','Timeframe','','text'],['d_e','Preço de entrada'],['d_x','Preço de saída'],['d_m','Margem'],['d_l','Alavancagem'],['d_st','Stop'],['d_tp','Take Profit'],['d_taxas','Taxas'],['d_fund','Funding'],['d_risco','Risco ($)']];
 return`<h2>Meu Diário</h2><div class="tabs"><a class="btn ${a?'alt':''}" href="#diario">Novo</a><a class="btn ${a=='hist'?'':'alt'}" href="#diario/hist">Histórico</a><a class="btn ${a=='est'?'':'alt'}" href="#diario/est">Estatísticas</a><a class="btn ${a=='banca'?'':'alt'}" href="#diario/banca">Banca</a></div>`+
 (a=='hist'?`<div class="card tbl"><table><tr><th>Data</th><th>Ativo</th><th>L/S</th><th>Líquido</th><th></th></tr>${S.trades.slice().reverse().map((x,i)=>`<tr><td>${x.data||''}</td><td>${x.ativo||''}</td><td>${x.side||''}</td><td class="${cls(x.net)}">${money(x.net)}</td><td><button onclick="delT(${S.trades.length-1-i})">🗑</button></td></tr>`).join('')}</table></div><button class="btn alt" onclick="exportCSV()">Exportar CSV</button>`
 :a=='est'?`<div class="card">${R('Total de operações',s.n)}${R('Positivas / Negativas',s.w+' / '+s.l)}${R('Taxa de acerto',pct(s.rate))}${R('Resultado bruto',money(s.bruto),cls(s.bruto))}${R('Taxas',money(s.taxas))}${R('Funding',money(s.fund))}${R('Resultado líquido',money(s.net),cls(s.net))}${R('Maior ganho',money(s.max))}${R('Maior perda',money(s.min))}${R('Média de ganho',money(s.mg))}${R('Média de perda',money(s.mp))}${R('Sequência de ganhos / perdas',s.mw+' / '+s.ml)}</div><div class="card"><b>Por ativo</b>${grpHTML(s.ativo)}<b>Por timeframe</b>${grpHTML(s.tf)}<b>Long / Short</b>${grpHTML(s.side)}</div><div class="card"><b>Resultado por operação</b><div class="hb">${S.trades.map(x=>`<i title="${money(x.net)}" style="height:${Math.max(4,Math.abs(x.net||0)/(Math.max(s.max,-s.min)||1)*100)}%;background:${x.net>=0?'var(--ok)':'var(--bad)'}"></i>`).join('')}</div></div><p class="mut">Estatísticas descritivas; não indicam desempenho futuro.</p>`
 :a=='banca'?bancaHTML()
 :`<div class="card"><label>Long/Short</label><select id="d_side"><option value="long">Long</option><option value="short">Short</option></select>${fld.map(([i,l,v,t])=>F(i,l,v||'',t||'number')).join('')}<p class="mut">Se deixar em branco, o resultado bruto é estimado por entrada/saída/margem/alavancagem.</p>${F('d_bruto','Resultado bruto (opcional)')}${[['d_why','Motivo da entrada'],['d_est','Estratégia utilizada'],['d_eb','Emoção antes da entrada'],['d_ea','Emoção depois da saída'],['d_ok','O que fiz certo?'],['d_no','O que fiz errado?'],['d_ap','O que aprendi?'],['d_nota','Print/anotação']].map(([i,l])=>`<label>${l}</label><textarea id="${i}"></textarea>`).join('')}<button class="btn" onclick="addT()">Salvar operação</button></div>`)},
config(){return`<h2>Configurações</h2><div class="card"><label>Tema</label><select onchange="S.cfg.theme=this.value;save();document.documentElement.dataset.theme=this.value"><option value="dark" ${S.cfg.theme=='dark'?'selected':''}>Escuro</option><option value="light" ${S.cfg.theme=='light'?'selected':''}>Claro</option></select><label>Moeda padrão</label><select onchange="S.cfg.moeda=this.value;save()"><option ${S.cfg.moeda=='USD'?'selected':''}>USD</option><option ${S.cfg.moeda=='BRL'?'selected':''}>BRL</option></select>${F('cfg_fx','Cotação USD/BRL',S.cfg.fx).replace('<input','<input onchange="S.cfg.fx=N(this.value)||5.5;save()"')}</div><button class="btn" onclick="exportJSON()">Exportar dados (JSON)</button><button class="btn alt" onclick="exportCSV()">Exportar diário (CSV)</button><label class="btn alt">Importar dados (JSON)<input type="file" accept=".json" hidden onchange="importJSON(this.files[0])"></label><button class="btn alt" style="color:var(--bad)" onclick="if(confirm('Apagar todos os dados?')){localStorage.removeItem(KEY);location.reload()}">Limpar dados</button>`+AVISO}};
function bancaHTML(){const b=S.bank,net=stats().net,cur=(b.cur||b.ini||0),v=b.ini?(cur-b.ini)/b.ini*100:NaN;
 return`<div class="card">${[['b_i','Banca inicial',b.ini],['b_c','Banca atual',b.cur],['b_me','Meta diária (opcional)',b.meta],['b_li','Limite diário de perda',b.lim],['b_r','Risco por operação (%)',b.risco]].map(([i,l,v])=>F(i,l,v||'')).join('')}<button class="btn" onclick="saveBanca()">Salvar banca</button>${R('Lucro/prejuízo',money(cur-b.ini),cls(cur-b.ini))}${R('Variação',pct(v))}${R('Resultado do diário',money(net),cls(net))}<b>Evolução</b><div class="hb">${b.hist.map(h=>`<i title="${h.v}" style="height:${Math.max(4,h.v/(Math.max(...b.hist.map(x=>x.v))||1)*100)}%"></i>`).join('')}</div></div>`}
function saveBanca(){const b=S.bank;b.ini=N(V('b_i'))||0;b.cur=N(V('b_c'))||0;b.meta=N(V('b_me'))||0;b.lim=N(V('b_li'))||0;b.risco=N(V('b_r'))||1;if(b.cur)b.hist.push({d:new Date().toISOString().slice(0,10),v:b.cur});save();render()}
function addT(){const g=N(V('d_e')),m=N(V('d_m')),l=N(V('d_l')),x=N(V('d_x')),side=V('d_side');let bruto=N(V('d_bruto'));
 if(!isFinite(bruto)){const r=calcFut({margem:m,lev:l,entrada:g,saida:x,side});bruto=r?r.bruto:0}
 const taxas=N(V('d_taxas'))||0,fund=N(V('d_fund'))||0;
 S.trades.push({data:V('d_data'),hora:V('d_hora'),ativo:V('d_ativo').toUpperCase(),side,tf:V('d_tf'),entrada:g,saida:x,margem:m,lev:l,stop:N(V('d_st')),tp:N(V('d_tp')),bruto,taxas,fund,net:bruto-taxas-fund,risco:N(V('d_risco'))||0,nota:V('d_nota'),motivo:V('d_why'),estrategia:V('d_est'),emoAntes:V('d_eb'),emoDepois:V('d_ea'),certo:V('d_ok'),errado:V('d_no'),aprendi:V('d_ap')});save();go('diario/rev/'+(S.trades.length-1))}
function delT(i){if(confirm('Excluir operação?')){S.trades.splice(i,1);save();render()}}
function ans(i,k){const q=QUIZ[i],ok=k==q[2];S.quiz[i]=ok;save();$('#fb').innerHTML=`<p class="${ok?'pos':'neg'}"><b>${ok?'Correto!':'Incorreto. Resposta: '+q[1][q[2]]}</b></p><p>${q[3]}</p><a class="btn" href="#quiz/${i+1}">Próxima</a>`}
function chk(){const c=S.check;c.ativo=V('c_ativo');c.tf=V('c_tf');c.tr=V('c_tr');c.h=V('c_h');c.j=V('c_j');c.e=V('c_e');c.s=V('c_s');c.p=V('c_p');c.t=V('c_t');save();
 const rr=calcRR(N(c.e),N(c.s),N(c.t));$('#c_o').innerHTML=(rr?R('Risco (por unidade)',rr.risco.toFixed(4))+R('Retorno potencial',rr.ret.toFixed(4))+R('Risco/retorno','1 : '+rr.rr.toFixed(2)):'<p class="mut">Preencha entrada, stop e alvo para calcular.</p>')+`<div class="card"><b>Checklist concluído.</b><p>Você definiu um cenário. Agora revise os riscos antes de executar.</p><button class="btn" onclick="regChk()">Registrar operação</button></div>`}
function regChk(){const c=S.check;S.trades.push({data:new Date().toISOString().slice(0,10),ativo:(c.ativo||'').toUpperCase(),side:c.h=='SHORT'?'short':'long',tf:c.tf,entrada:N(c.e),stop:N(c.s),tp:N(c.t),bruto:0,taxas:0,fund:0,net:0,motivo:c.j});save();go('diario/hist')}
function sim(){const r=calcFut({margem:N(V('s_m')),lev:N(V('s_l')),entrada:N(V('s_e')),saida:N(V('s_x')),side:V('s_s'),fe:0.05,fs:0.05});if(!r)return $('#s_o').innerHTML='<p class="neg">Valores inválidos.</p>';S.sims++;save();
 $('#s_o').innerHTML=R('Posição',money(r.pos,'USD'))+R('Variação',pct(r.var_))+R('Resultado líquido (taxas 0,05%+0,05%)',money(r.liq,'USD'),cls(r.liq))+R('Banca fictícia final',money(N(V('s_b'))+r.liq,'USD'))+R('Liquidação aprox.',money(r.liqPx,'USD'))+'<p class="mut"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b></p>'}
function calcK(){const r=calcFut({margem:N(V('k_m')),lev:N(V('k_l')),entrada:N(V('k_e')),saida:N(V('k_x')),side:V('k_s'),fe:N(V('k_fe'))||0,fs:N(V('k_fs'))||0,fund:N(V('k_fu'))||0});
 $('#k_o').innerHTML=r?R('Valor da posição',money(r.pos,'USD'))+R('Quantidade',(r.pos/N(V('k_e'))).toFixed(6))+R('Variação do ativo (lado)',pct(r.var_))+R('PnL bruto',money(r.bruto,'USD'),cls(r.bruto))+R('Taxas estimadas',money(r.taxas,'USD'))+R('Funding estimado',money(r.fundv,'USD'))+R('PnL líquido estimado',money(r.liq,'USD'),cls(r.liq))+R('Retorno sobre a margem',pct(r.roi),cls(r.roi))+R('Liquidação (aprox., genérico)',money(r.liqPx,'USD')):'<p class="mut">Informe margem, alavancagem ≥ 1 e entrada > 0.</p>'}
function calcA(){const m=N(V('a_m')),l=N(V('a_l'));if(!(m>0&&l>=1))return $('#a_o').innerHTML='<p class="mut">Valores inválidos.</p>';
 $('#a_o').innerHTML=R('MARGEM',money(m,'USD'))+R('VALOR DA POSIÇÃO',money(m*l,'USD'))+[1,5,10,-1,-5,-10].map(p=>R('Ativo '+(p>0?'+':'')+p+'%','PnL bruto ≈ '+money(m*l*p/100,'USD'),cls(p))).join('')}
function calcR(){const r=calcRisco({banca:N(V('r_b')),r:N(V('r_r')),entrada:N(V('r_e')),stop:N(V('r_s')),lev:N(V('r_l'))});
 $('#r_o').innerHTML=r?R('Risco máximo em dinheiro',money(r.rd,'USD'))+R('Distância até o stop',r.dist.toFixed(4)+' ('+pct(r.distP)+')')+R('Tamanho estimado da posição',money(r.pos,'USD'))+R('Quantidade',r.qtd.toFixed(6))+R('Margem necessária',money(r.margem,'USD'))+`<p class="mut">Cálculo: risco ($) ÷ distância até o stop = quantidade; quantidade × entrada = posição. A margem não é o risco: o risco é o que você perde se o stop for atingido.${r.pctBanca>100*N(V('r_l'))?'':''}</p>`:'<p class="mut">Informe valores válidos (entrada ≠ stop).</p>'}
function calcF(){const v=N(V('f_v')),c=N(V('f_c'));$('#f_o').innerHTML=v>=0&&c>0?R('Resultado',V('f_d')=='u'?money(v*c,'BRL'):money(v/c,'USD')):'<p class="mut">Valores inválidos.</p>'}
function go(h){location.hash=h}
function render(){const[h,a,b]=(location.hash.slice(1)||'inicio').split('/'),v=views[h]||views.inicio;app.innerHTML=v(a,b);document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('on',x.getAttribute('href')=='#'+(({quiz:'aprender',treino:'aprender',biblio:'aprender',indic:'aprender',estrat:'aprender',plano:'aprender',gloss:'aprender',nao:'analisar',riscos:'inicio'})[h]||h)));scrollTo(0,0);
 ({biblio:()=>bib(),gloss:()=>gl(),calc:()=>({undefined:calcK,alav:calcA,risco:calcR,cambio:calcF,mais:calcM}[a]||calcK)()})[h]?.()}
/* ===== v2: academia guiada ===== */
const LESS=[];MODULOS.forEach((m,i)=>m.a.forEach((_,j)=>LESS.push([i,j])));
const ad=(i,j)=>S.aulas[i+'.'+j];
const modFrac=ms=>{let t=0,d=0;ms.forEach(i=>MODULOS[i].a.forEach((_,j)=>{t++;if(ad(i,j))d++}));return t?d/t:0};
const nextLesson=ms=>{for(const i of ms)for(let j=0;j<MODULOS[i].a.length;j++)if(!ad(i,j))return[i,j]};
const ETAPAS=[['Fundamentos','Entenda futuros, margem e liquidação.',()=>modFrac([0]),[0]],['Gráficos','Candles, suporte/resistência e estrutura.',()=>modFrac([2,3,7]),[2,3,7]],['Indicadores','Médias, volume, RSI e MACD.',()=>modFrac([4,5,6]),[4,5,6]],['Gestão de risco','Alavancagem, stop e risco por operação.',()=>modFrac([1]),[1]],['Estratégia','Estratégias e psicologia.',()=>modFrac([8,9]),[8,9]],['Simulação','Salve 5 simulações.',()=>Math.min(1,S.simsList.length/5),0,'analisar/sim'],['Checklist de operação','Conclua o checklist guiado.',()=>S.checkDone?1:0,0,'analisar'],['Diário','Registre 3 operações.',()=>Math.min(1,S.trades.length/3),0,'diario'],['Revisão de desempenho','Faça 1 revisão pós-operação.',()=>Math.min(1,S.revs),0,'diario/hist'],['Preparação para operação real','Leia os riscos e confirme seus limites.',()=>S.prep?1:0,0,'riscos']];
const etHref=e=>{const nl=e[3]&&nextLesson(e[3]);return nl?`aprender/${nl[0]}/${nl[1]}`:e[3]?'aprender/'+e[3][0]:e[4]};
views.inicio=()=>{const fr=ETAPAS.map(e=>e[2]()),n=fr.filter(x=>x>=1).length,k=fr.findIndex(x=>x<1),s=stats(),p=prog(),nx=ETAPAS[k],nl=nx&&nx[3]?nextLesson(nx[3]):null;
 const txt=k<0?'Você concluiu as 10 etapas. Continue registrando e revisando.':`Você concluiu ${n} de 10 etapas.<br><b>Próximo passo:</b> ${nl?'aprender "'+MODULOS[nl[0]].a[nl[1]][0]+'"':nx[0]+' — '+nx[1]}`;
 return`<h2>Bem-vindo à Futures Trader Academy</h2><p class="mut">Antes de pensar em operar, aprenda a analisar, controlar o risco e montar um plano.</p>
 <div class="card"><b>SEU CAMINHO DE APRENDIZADO</b><p>${txt}</p><a class="btn" href="#${k<0?'diario':etHref(nx)}">CONTINUAR MEU ESTUDO</a></div>
 <div class="grid"><div class="card"><span class="mut">Módulos</span><div class="kpi">${p.m}/${MODULOS.length}</div></div><div class="card"><span class="mut">Aulas</span><div class="kpi">${Object.keys(S.aulas).length}/${LESS.length}</div></div><div class="card"><span class="mut">Quizzes</span><div class="kpi">${Object.values(S.mq).filter(Boolean).length}/${MODULOS.length}</div></div><div class="card"><span class="mut">Simulações</span><div class="kpi">${S.simsList.length}</div></div><div class="card"><span class="mut">Operações</span><div class="kpi">${s.n}</div></div></div>
 <div class="grid"><a class="btn alt" href="#analisar">✅ Checklist</a><a class="btn alt" href="#analisar/sim">🧪 Simulador</a><a class="btn alt" href="#plano">📅 Plano</a><a class="btn alt" href="#diario">📝 Diário</a></div>
 ${ETAPAS.map((e,i)=>{const f=fr[i];return`<div class="card step ${f>=1?'ok':''}"><b>${f>=1?'✅':i==k?'👉':'▫️'} Etapa ${i+1} — ${e[0]}</b><p class="mut">${e[1]}${i?'<br>Pré-requisito: etapa '+i+' ('+ETAPAS[i-1][0]+')':''}</p>${bar(Math.round(f*100))}<a class="btn alt" href="#${etHref(e)}">Continuar</a></div>`}).join('')}<a class="btn alt" href="#treino">🎯 Modo Treinamento</a><a class="btn alt" href="#riscos">⚠️ Riscos do mercado futuro</a>`+AVISO};
const lnk=(h,t)=>`<a class="card" style="display:block;text-decoration:none;color:inherit" href="#${h}">${t}</a>`;
views.aprender=(a,b)=>{if(a===undefined)return`<h2>Aprender</h2>${MODULOS.map((m,i)=>{const f=modFrac([i]);return lnk('aprender/'+i,`<b>${f>=1?'✅':'▫️'} ${m.t}</b>${bar(Math.round(f*100))}`)}).join('')}<div class="grid"><a class="btn alt" href="#plano">📅 Plano de estudos</a><a class="btn alt" href="#biblio">📚 Biblioteca</a><a class="btn alt" href="#indic">📈 Indicadores</a><a class="btn alt" href="#treino">🎯 Modo Treinamento</a><a class="btn alt" href="#estrat">♟️ Estratégias</a><a class="btn alt" href="#gloss">📝 Glossário</a><a class="btn alt" href="#nao">⛔ Quando não operar</a><a class="btn alt" href="#quiz">🎯 Quiz geral (${prog().qp}%)</a></div>`;
 const i=+a,m=MODULOS[i];if(!m)return views.aprender();
 if(b!==undefined){const j=+b,x=m.a[j];if(!x)return views.aprender(a);return`<a href="#aprender/${i}">← ${m.t}</a><h2>${x[0]}</h2><div class="card">${x[1]}</div><button class="btn ok" onclick="fim(${i},${j})">${ad(i,j)?'Aula concluída · continuar':'Concluir aula'}</button>`+AVISO}
 return`<a href="#aprender">← Módulos</a><h2>${m.t}</h2>${m.a.map((x,j)=>lnk(`aprender/${i}/${j}`,(ad(i,j)?'✅ ':'▫️ ')+x[0])).join('')}<div class="card"><b>Quiz do módulo</b> ${S.mq[i]?'✅':''}<p>${m.q[0]}</p>${m.q[1].map((o,k)=>`<button class="btn alt opt" onclick="mAns(${i},${k})">${o}</button>`).join('')}<div id="fb"></div></div>`};
function fim(i,j){S.aulas[i+'.'+j]=true;save();go(j+1<MODULOS[i].a.length?`aprender/${i}/${j+1}`:`aprender/${i}`)}
function mAns(i,k){const q=MODULOS[i].q,ok=k==q[2];S.mq[i]=S.mq[i]||ok;save();$('#fb').innerHTML=`<p class="${ok?'pos':'neg'}"><b>${ok?'Correto!':'Incorreto.'}</b> ${q[3]}</p><button class="btn alt" onclick="render()">Tentar novamente</button>`}
views.plano=()=>{const n=S.plano.n,per=Math.ceil(LESS.length/n);return`<a href="#aprender">← Aprender</a><h2>Meu Plano de Estudos</h2><label>Duração (dias)</label><select onchange="S.plano.n=+this.value;save();render()">${[7,14,30].map(x=>`<option ${x==n?'selected':''}>${x}</option>`).join('')}</select>`+Array.from({length:n},(_,d)=>{const L=LESS.slice(d*per,d*per+per);return`<div class="card"><label style="color:var(--tx)"><input type="checkbox" style="width:auto;min-height:0" ${S.plano.done[d]?'checked':''} onchange="S.plano.done[${d}]=this.checked;save()"> <b>DIA ${d+1}</b></label><p>📖 ${L.length?L.map(([i,j])=>`<a href="#aprender/${i}/${j}">${MODULOS[i].a[j][0]}</a>`).join(', '):'Revisão geral dos módulos e do diário'}</p><p class="mut">Leitura: glossário · Exercício: explique a aula com suas palavras · Quiz do módulo · 1 simulação · Revisão</p></div>`}).join('')};
views.gloss=()=>`<a href="#aprender">← Aprender</a><h2>Glossário</h2><input id="gq" placeholder="Buscar termo…" oninput="gl()"><div id="gl"></div>`;
function gl(){const q=(V('gq')||'').toLowerCase();$('#gl').innerHTML=GLOS.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q)).map(x=>`<div class="card"><b>${x[0]}</b><br>${x[1]}</div>`).join('')||'<p class="mut">Nada encontrado.</p>'}
views.nao=()=>`<a href="#analisar">← Analisar</a><h2>QUANDO NÃO OPERAR</h2><div class="card">${['Mercado sem direção','Entrada sem stop definido','Risco acima do limite','Tentativa de recuperar prejuízo','Operação baseada em emoção','Entrada após movimento exagerado','Falta de confluência','Você não sabe explicar o motivo da operação','Tamanho da posição incompatível com a banca'].map(x=>`<p>⛔ ${x}</p>`).join('')}<p><b>Não operar também é uma decisão válida.</b></p></div>`;
views.riscos=()=>{const ok=ETAPAS.slice(0,9).every(e=>e[2]()>=1);return`<h2>RISCOS DO MERCADO FUTURO</h2><div class="card">${['Perdas podem ocorrer rapidamente.','Alavancagem aumenta a exposição.','Liquidação pode ocorrer.','Stop não elimina todos os riscos.','O preço pode sofrer movimentos bruscos.','Taxas e funding impactam os resultados.','Dados de mercado podem variar entre corretoras.','Resultados passados não garantem resultados futuros.'].map(x=>`<p>• ${x}</p>`).join('')}<p><b>Este aplicativo é exclusivamente educacional e não constitui recomendação financeira.</b></p></div>${S.prep?'<p class="pos">Etapa 10 concluída.</p>':ok?'<button class="btn ok" onclick="S.prep=true;save();render()">Li e entendi os riscos</button>':'<p class="mut">Conclua as etapas 1–9 para liberar a etapa 10.</p>'}`};
/* checklist guiado */
const WZ=[['Contexto',[['ativo','Qual ativo estou analisando?','t'],['tf','Qual timeframe?','t'],['tend','Tendência ou lateralização?','s:Tendência de alta|Tendência de baixa|Lateralização'],['mov','Existe movimento claro?','y']]],['Estrutura',[['hh','Existe HH/HL?','y'],['lh','Existe LH/LL?','y'],['mud','Houve mudança de estrutura?','y'],['niv','Onde estão os principais níveis?','t']]],['Suporte e resistência',[['sup','Onde está o suporte?','n'],['res','Onde está a resistência?','n'],['prox','O preço está próximo de alguma zona importante?','y']]],['Médias',[['mm','Onde está a MM/EMA?','t'],['acima','O preço está acima ou abaixo?','s:Acima|Abaixo|Sobre a média'],['incl','As médias estão inclinadas?','y'],['cruz','Existe cruzamento?','y'],['alin','As médias estão alinhadas?','y']]],['Volume',[['vol','O volume está aumentando?','y'],['conf','O movimento possui confirmação de volume?','y'],['div','Existe divergência entre preço e volume?','y']]],['Confirmação',[['conflu','Existe confluência?','y'],['claro','O cenário está claro?','y'],['motivo','Existe motivo objetivo para a operação?','y'],['inval','O cenário está invalidado?','y']]],['Risco',[['perde','Quanto estou disposto a perder ($)?','n'],['stop','Onde fica o stop?','n'],['tam','Qual é o tamanho da posição?','n'],['lev','Qual é a alavancagem?','n'],['dentro','O risco está dentro do limite definido?','y']]],['Plano',[['p_ativo','Ativo','t'],['p_side','Long ou Short','s:Long|Short'],['p_e','Preço de entrada','n'],['p_sl','Stop Loss','n'],['p_tp','Take Profit','n'],['p_r','Risco em $','n'],['p_tam','Tamanho da posição','n'],['p_lev','Alavancagem','n'],['p_mot','Motivo da operação','t']]]];
function fld(k,l,t){const v=String(S.wz.d[k]??'').replace(/"/g,'&quot;'),on=`onchange="S.wz.d.${k}=this.value;save()"`;
 if(t=='y'||t[0]=='s')return`<label>${l}</label><select ${on}><option value=""></option>${(t=='y'?['Sim','Não']:t.slice(2).split('|')).map(x=>`<option ${v==x?'selected':''}>${x}</option>`).join('')}</select>`;
 return`<label>${l}</label><input ${on} type="${t=='n'?'number':'text'}" inputmode="${t=='n'?'decimal':'text'}" step="any" value="${v}">`}
function wzGo(n){S.wz.i=Math.max(0,Math.min(8,n));save();render()}
function wzView(){const i=S.wz.i;if(i>7)return wzFinal();const st=WZ[i];return`<div class="card"><b>CHECKLIST ANTES DA OPERAÇÃO</b><p class="mut">Etapa ${i+1} de 9 — ${st[0]}</p>${bar((i+1)/9*100)}${st[1].map(f=>fld(...f)).join('')}<div class="grid"><button class="btn alt" onclick="wzGo(${i-1})">← Anterior</button><button class="btn" onclick="wzGo(${i+1})">Próxima →</button></div><a href="#nao">Quando não operar?</a></div>`}
function wzFinal(){const d=S.wz.d,e=N(d.p_e),sl=N(d.p_sl),tp=N(d.p_tp),r=N(d.p_r),w=[],rr=calcRR(e,sl,tp),lim=(S.bank.cur||S.bank.ini||0)*(S.bank.rop||S.bank.risco||1)/100;
 if(!(sl>0)||sl===e)w.push('Stop não definido ou igual à entrada.');if(!d.p_mot)w.push('Motivo da operação não explicado.');if(d.inval=='Sim')w.push('Você indicou que o cenário está invalidado.');if(d.claro=='Não'||d.conflu=='Não'||d.motivo=='Não')w.push('Falta clareza, confluência ou motivo objetivo.');if(d.dentro=='Não'||(lim>0&&r>lim))w.push('Risco acima do limite definido.');if(rr&&rr.rr<1)w.push('Relação risco/retorno abaixo de 1:1.');
 const D={ok:'🟢 PLANO APROVADO PARA SIMULAÇÃO',espera:'🟡 AINDA PRECISA DE CONFIRMAÇÃO',nao:'🔴 NÃO OPERAR'};
 return`<div class="card"><b>Etapa 9 — Decisão final</b>${R('Ativo / lado',(d.p_ativo||'—')+' / '+(d.p_side||'—'))}${R('Entrada · Stop · Alvo',[e,sl,tp].map(x=>isFinite(x)?x:'—').join(' · '))}${R('Risco / retorno',rr?'1 : '+rr.rr.toFixed(2):'—')}${R('Risco em $',money(r,'USD'))}${w.length?`<p class="neg"><b>Pontos de atenção:</b></p>${w.map(x=>`<p>• ${x}</p>`).join('')}`:'<p class="mut">Nenhum ponto de atenção automático. Ainda assim, revise.</p>'}<p class="mut">O app não recomenda operações. A decisão final é sua:</p>${Object.entries(D).map(([k,v])=>`<button class="btn ${S.wz.dec==k?'':'alt'}" onclick="wzDec('${k}')">${v}</button>`).join('')}${S.wz.dec?`<p><b>Checklist concluído.</b> Você definiu um cenário. Agora revise os riscos antes de executar.</p>${S.wz.dec=='ok'?'<button class="btn" onclick="wzSim()">Simular este plano</button><button class="btn alt" onclick="wzReg()">Registrar operação</button>':''}`:''}<button class="btn alt" onclick="wzGo(7)">← Editar plano</button><button class="btn alt" onclick="S.wz={i:0,d:{}};save();render()">Novo checklist</button></div>`}
function wzDec(k){S.wz.dec=k;S.checkDone=true;save();render()}
function wzSim(){const d=S.wz.d;S.simPre={a:d.p_ativo,tf:d.tf,s:(d.p_side||'Long').toLowerCase(),e:d.p_e,sl:d.p_sl,tp:d.p_tp,l:d.p_lev};save();go('analisar/sim')}
function wzReg(){const d=S.wz.d;S.trades.push({data:new Date().toISOString().slice(0,10),ativo:(d.p_ativo||'').toUpperCase(),side:(d.p_side||'Long').toLowerCase(),tf:d.tf,entrada:N(d.p_e),stop:N(d.p_sl),tp:N(d.p_tp),risco:N(d.p_r)||0,lev:N(d.p_lev),bruto:0,taxas:0,fund:0,net:0,motivo:d.p_mot});save();go('diario/rev/'+(S.trades.length-1))}
views.analisar=a=>`<div class="tabs">${[['','Checklist'],['tec','Mapa'],['sim','Simulador']].map(([k,n])=>`<a class="btn ${(a||'')==k?'':'alt'}" href="#analisar${k?'/'+k:''}">${n}</a>`).join('')}<a class="btn alt" href="#nao">Não operar</a></div>`+(a=='tec'?mapaForm():a=='sim'?simForm():wzView());
/* mapa da análise */
function mapaForm(){const S_=(id,l,o)=>`<label>${l}</label><select id="${id}">${o.map(x=>`<option>${x}</option>`).join('')}</select>`;return`<div class="card"><b>Análise guiada</b>${F('m_a','Ativo','','text')}${F('m_tf','Timeframe','','text')}${F('m_p','Preço atual')}${S_('m_t','Tendência',['Alta','Baixa','Lateral'])}${F('m_s','Suporte')}${F('m_r','Resistência')}${S_('m_m','Preço vs médias',['Acima','Abaixo','Misto'])}${S_('m_v','Volume',['Crescente','Decrescente','Neutro'])}${F('m_rsi','RSI (0–100)')}${S_('m_ma','MACD',['Positivo','Negativo','Neutro'])}<label>Contexto</label><textarea id="m_c"></textarea><button class="btn" onclick="mapa()">Montar mapa da análise</button><div id="m_o"></div></div>`}
function mapa(){const p=N(V('m_p')),s=N(V('m_s')),r=N(V('m_r')),t=V('m_t'),m=V('m_m'),v=V('m_v'),rsi=N(V('m_rsi')),mc=V('m_ma');if(!(p>0))return $('#m_o').innerHTML='<p class="neg">Informe o preço atual.</p>';
 const up=t=='Alta'&&m=='Acima'&&mc=='Positivo',dn=t=='Baixa'&&m=='Abaixo'&&mc=='Negativo',c=[],at=[];
 if(t=='Alta'&&m=='Acima')c.push('Tendência de alta com preço acima das médias');if(t=='Baixa'&&m=='Abaixo')c.push('Tendência de baixa com preço abaixo das médias');if((t=='Alta'&&mc=='Positivo')||(t=='Baixa'&&mc=='Negativo'))c.push('MACD alinhado à tendência');if(v=='Crescente'&&t!='Lateral')c.push('Volume crescente acompanhando o movimento');
 if(t=='Lateral')at.push('Mercado sem direção clara');if(v=='Decrescente')at.push('Volume caindo: risco de falso rompimento');if(rsi>=70)at.push('RSI esticado para cima');if(rsi<=30)at.push('RSI esticado para baixo');if(m=='Misto')at.push('Médias sem alinhamento');if(s>0&&Math.abs(p-s)/p<.01)at.push('Preço próximo do suporte');if(r>0&&Math.abs(r-p)/p<.01)at.push('Preço próximo da resistência');
 const rs=r>0?r:'a resistência',ss=s>0?s:'o suporte',L=x=>x.length?x.map(y=>`<p>• ${y}</p>`).join(''):'<p class="mut">Nenhum destacado.</p>';
 $('#m_o').innerHTML=`<h3>MAPA DA ANÁLISE</h3>${R('Contexto',(V('m_a')||'—')+' · '+(V('m_tf')||'—')+' · '+t)}<p>${V('m_c')}</p><b>Confluências encontradas</b>${L(c)}<b>Pontos de atenção</b>${L(at)}<b>Possíveis cenários</b><p><b>A:</b> se o preço romper ${rs} com confirmação de volume, a ideia de continuação de alta ganha força.</p><p><b>B:</b> se houver rejeição em ${rs} (pavio longo, volume alto), ganha força a ideia de recuo até ${ss}.</p><p><b>C:</b> se o preço perder ${ss}, o cenário de alta perde validade e a estrutura pode mudar.</p>${R('Nível de invalidação',up?String(ss):dn?String(rs):'defina antes de qualquer plano')}<p class="mut"><b>Risco:</b> nenhum cenário é certeza. Defina o stop antes e calcule o tamanho da posição. Isto não é recomendação.</p>`}
/* simulador */
function simCalc(o){const rk=calcRisco({banca:o.b,r:o.r,entrada:o.e,stop:o.sl,lev:o.l});if(!rk)return null;const d=o.side=='short'?-1:1;if((o.sl-o.e)*d>=0)return{err:'O stop deve ficar abaixo da entrada no Long e acima no Short.'};const dtp=isFinite(o.tp)?(o.tp-o.e)*d:NaN,pnl=isFinite(o.x)?rk.qtd*(o.x-o.e)*d:NaN;return{...rk,dtp,rr:dtp/rk.dist,pnl,imp:pnl/o.b*100}}
function simForm(){const P=S.simPre||{},b=S.bank.cur||S.bank.ini||1000;return`<div class="card"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b>${F('s_a','Ativo',P.a||'','text')}${F('s_tf','Timeframe',P.tf||'','text')}<label>Long/Short</label><select id="s_s"><option value="long">Long</option><option value="short" ${P.s=='short'?'selected':''}>Short</option></select>${F('s_e','Entrada',P.e||'')}${F('s_sl','Stop Loss',P.sl||'')}${F('s_tp','Take Profit',P.tp||'')}${F('s_x','Preço de saída (resultado)')}${F('s_b','Banca fictícia',b)}${F('s_r','Risco %',S.bank.rop||S.bank.risco||1)}${F('s_l','Alavancagem',P.l||5)}<button class="btn alt" onclick="simRun(0)">Calcular</button><button class="btn" onclick="simRun(1)">Salvar simulação</button><div id="s_o"></div></div>`+simHist()}
function simRun(sv){const o={a:V('s_a').toUpperCase(),tf:V('s_tf'),side:V('s_s'),e:N(V('s_e')),sl:N(V('s_sl')),tp:N(V('s_tp')),x:N(V('s_x')),b:N(V('s_b')),r:N(V('s_r')),l:N(V('s_l'))},c=simCalc(o);
 if(!c||c.err)return $('#s_o').innerHTML=`<p class="neg">${c?c.err:'Preencha banca, risco %, entrada e stop com valores válidos.'}</p>`;
 $('#s_o').innerHTML=R('Valor arriscado',money(c.rd,'USD'))+R('Distância até o stop',c.dist.toFixed(4)+' ('+pct(c.distP)+')')+R('Distância até o alvo',isFinite(c.dtp)?c.dtp.toFixed(4):'—')+R('Risco/retorno',isFinite(c.rr)?'1 : '+c.rr.toFixed(2):'—')+R('Posição / margem',money(c.pos,'USD')+' / '+money(c.margem,'USD'))+R('PnL estimado',isFinite(c.pnl)?money(c.pnl,'USD'):'—',cls(c.pnl))+R('Impacto na banca',isFinite(c.imp)?pct(c.imp):'—',cls(c.imp))+'<p class="mut">SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</p>';
 if(sv){if(!isFinite(c.pnl))return alert('Informe o preço de saída para salvar.');S.simsList.push({...o,rd:c.rd,rr:c.rr,pnl:c.pnl,data:new Date().toISOString().slice(0,10)});S.sims=S.simsList.length;S.simPre=null;save();render()}}
function simHist(){const L=S.simsList;if(!L.length)return'<p class="mut">Sem simulações salvas.</p>';const w=L.filter(x=>x.pnl>0),l=L.filter(x=>x.pnl<0),av=a=>a.length?a.reduce((s,x)=>s+x.pnl,0)/a.length:0;let eq=0,pk=0,dd=0,sq=0,ms=0;L.forEach(x=>{eq+=x.pnl;pk=Math.max(pk,eq);dd=Math.max(dd,pk-eq);sq=x.pnl<0?sq+1:0;ms=Math.max(ms,sq)});
 return`<div class="card"><b>Estatísticas das simulações</b>${R('Simulações',L.length)}${R('Ganhos / Perdas',w.length+' / '+l.length)}${R('Taxa de acerto',pct(w.length/L.length*100))}${R('Média de ganho',money(av(w),'USD'))}${R('Média de perda',money(av(l),'USD'))}${R('Maior sequência de perdas',ms)}${R('Drawdown máximo',money(dd,'USD'),'neg')}<p class="mut">Descritivo; não indica desempenho futuro.</p></div><div class="card tbl"><table><tr><th>Data</th><th>Ativo</th><th>L/S</th><th>R:R</th><th>PnL</th></tr>${L.slice().reverse().slice(0,30).map(x=>`<tr><td>${x.data}</td><td>${x.a}</td><td>${x.side}</td><td>${isFinite(x.rr)?x.rr.toFixed(2):'—'}</td><td class="${cls(x.pnl)}">${money(x.pnl,'USD')}</td></tr>`).join('')}</table></div><button class="btn alt" onclick="if(confirm('Apagar simulações?')){S.simsList=[];S.sims=0;save();render()}">Limpar simulações</button>`}
/* calculadoras extras */
function maisHTML(o){const h0=o('mais'),tabs=h0.slice(0,h0.indexOf('</div>')+6),I=(i,l,v)=>F(i,l,v).replace('<input','<input oninput="calcM()"');return tabs+`<div class="card"><b>Preço médio</b>${I('pm_e1','Entrada 1',100)}${I('pm_q1','Quantidade 1',1)}${I('pm_e2','Entrada 2',90)}${I('pm_q2','Quantidade 2',1)}<div id="pm_o"></div></div><div class="card"><b>Impacto da perda na banca</b>${I('im_p','Perda na banca (%)',10)}<div id="im_o"></div></div><div class="card"><b>Take profit por risco/retorno</b>${I('tp_e','Entrada',100)}${I('tp_s','Stop',98)}${I('tp_r','Risco/retorno desejado',2)}<div id="tp_o"></div></div><div class="card warn"><b>ESTIMATIVA EDUCACIONAL.</b><p>O preço real de liquidação depende da corretora, contrato, margem, modo de margem, taxas, funding e regras específicas da plataforma.</p>${I('lq_e','Entrada',100)}${I('lq_l','Alavancagem',10)}<label>Lado</label><select id="lq_s" onchange="calcM()"><option value="long">Long</option><option value="short">Short</option></select><div id="lq_o"></div></div>`}
function calcM(){const q=(id,h)=>$('#'+id).innerHTML=h,bad='<p class="mut">Valores inválidos.</p>',e1=N(V('pm_e1')),q1=N(V('pm_q1')),e2=N(V('pm_e2')),q2=N(V('pm_q2'));
 q('pm_o',q1+q2>0&&e1>0&&e2>0?R('Preço médio',((e1*q1+e2*q2)/(q1+q2)).toFixed(4))+R('Quantidade total',q1+q2):bad);const p=N(V('im_p'));q('im_o',p>0&&p<100?R('Ganho necessário para recuperar',pct(p/(100-p)*100)):bad);
 const e=N(V('tp_e')),s=N(V('tp_s')),r=N(V('tp_r'));q('tp_o',e>0&&s>0&&e!==s&&r>0?R('Take profit',(e+(e-s)*r).toFixed(4))+R('Distância até o stop',Math.abs(e-s).toFixed(4)):bad);
 const c=calcFut({margem:1,lev:N(V('lq_l')),entrada:N(V('lq_e')),saida:NaN,side:V('lq_s')});q('lq_o',c?R('Estimativa genérica (NÃO é o preço real)',c.liqPx.toFixed(4)):bad)}
views.calc=(o=>a=>a=='mais'?maisHTML(o):o(a))(views.calc);
/* diário: revisão pós-operação */
const REV=[['Segui meu plano?','y'],['Respeitei o stop?','y'],['Respeitei o risco?','y'],['Entrei por estratégia ou emoção?','Estratégia|Emoção'],['O cenário realmente existia?','y'],['O que eu faria diferente?','t']];
function revHTML(i){const t=S.trades[i];if(!t)return views.diario();const v=t.rev||[];return`<h2>REVISÃO DA OPERAÇÃO</h2><div class="card"><p class="mut">${t.ativo||''} ${t.side||''} ${t.data||''}</p>${REV.map(([l,ty],k)=>`<label>${k+1}. ${l}</label>${ty=='t'?`<textarea id="rv${k}">${v[k]||''}</textarea>`:`<select id="rv${k}"><option></option>${(ty=='y'?['Sim','Não']:ty.split('|')).map(o=>`<option ${v[k]==o?'selected':''}>${o}</option>`).join('')}</select>`}`).join('')}<button class="btn" onclick="revSave(${i})">Salvar revisão</button><a class="btn alt" href="#diario/hist">Pular</a></div>`}
function revSave(i){const t=S.trades[i];if(!t.rev)S.revs++;t.rev=REV.map((_,k)=>V('rv'+k));save();go('diario/hist')}
views.diario=(o=>(a,b)=>a=='rev'?revHTML(+b):o(a))(views.diario);
/* gestão de banca */
function bancaHTML(){const b=S.bank,s=stats(),ini=b.ini||0,atual=ini?ini+s.net:(b.cur||0),hoje=new Date().toISOString().slice(0,10),T=S.trades.filter(x=>x.data==hoje),loss=a=>-a.reduce((z,x)=>z+Math.min(0,x.net||0),0),perdaH=loss(T),riscoH=T.reduce((z,x)=>z+(x.risco||0),0),perdaS=loss(S.trades.filter(x=>Date.now()-new Date(x.data)<7*864e5));
 let eq=ini,pk=ini,dd=0;S.trades.forEach(x=>{eq+=x.net||0;pk=Math.max(pk,eq);dd=Math.max(dd,pk-eq)});
 const rmax=ini*(b.rdia||0)/100,ld=b.ldia||b.lim||0,al=[];if(ld>0&&perdaH>=ld)al.push('Você já atingiu seu limite de perda diária.');if(rmax>0&&riscoH>=rmax)al.push('Você já atingiu seu limite de risco diário.');if(b.lsem>0&&perdaS>=b.lsem)al.push('Você já atingiu seu limite de perda semanal.');if(b.maxops>0&&T.length>=b.maxops)al.push('Você já atingiu o máximo de operações do dia.');
 return`<h3>GESTÃO DE BANCA</h3><div class="card">${[['b_i','Banca inicial',b.ini],['b_r','Risco máximo por operação (%)',b.rop||b.risco],['b_rd','Risco máximo diário (%)',b.rdia],['b_li','Limite de perda diária ($)',ld],['b_ls','Limite de perda semanal ($)',b.lsem],['b_mo','Máx. operações por dia',b.maxops]].map(([i,l,v])=>F(i,l,v||'')).join('')}${F('b_ob','Objetivo de estudo',b.obj||'','text')}<button class="btn" onclick="saveBanca()">Salvar</button></div><div class="card">${R('Banca atual',money(atual))}${R('Lucro/prejuízo acumulado',money(s.net),cls(s.net))}${R('Drawdown máximo',money(dd),'neg')}${R('Risco utilizado hoje',money(riscoH)+(rmax?' de '+money(rmax):''))}${R('Limite de perda restante hoje',ld?money(Math.max(0,ld-perdaH)):'—')}${al.map(x=>`<p class="neg"><b>${x}</b> Considere encerrar o treinamento por hoje.</p>`).join('')}<p class="mut">Nunca aumente o risco para recuperar perdas.</p></div>`}
function saveBanca(){const b=S.bank;b.ini=N(V('b_i'))||0;b.rop=b.risco=N(V('b_r'))||1;b.rdia=N(V('b_rd'))||0;b.ldia=b.lim=N(V('b_li'))||0;b.lsem=N(V('b_ls'))||0;b.maxops=N(V('b_mo'))||0;b.obj=V('b_ob');b.cur=b.ini+stats().net;if(b.ini)b.hist.push({d:new Date().toISOString().slice(0,10),v:b.cur});save();render()}
/* ===== v3: treinamento e estratégias ===== */
S.tr=S.tr||{};
const trScore=i=>Object.values(S.tr[i]||{}).filter(Boolean).length;
views.treino=a=>{if(a===undefined)return`<a href="#aprender">← Aprender</a><h2>Modo Treinamento</h2><p class="mut">Dados fictícios e educacionais. Não são sinais de mercado real.</p>`+TREINOS.map((x,i)=>lnk('treino/'+i,`<b>${x.t}</b><br><span class="mut">${x.ativo} · ${x.tf} · acertos: ${trScore(i)}/${x.q.length}</span>`)).join('');
 const i=+a,x=TREINOS[i];if(!x)return views.treino();
 return`<a href="#treino">← Cenários</a><h2>${x.t}</h2><div class="card warn"><b>TREINAMENTO — DADOS FICTÍCIOS</b>${R('Ativo / timeframe',x.ativo+' · '+x.tf)}${x.d.map(r=>R(r[0],r[1])).join('')}</div>`+x.q.map((q,n)=>`<div class="card"><b>${n+1}. ${q[0]}</b>${q[1].map((o,k)=>`<button class="btn alt opt" onclick="tAns(${i},${n},${k})">${o}</button>`).join('')}<div id="tq${n}"></div></div>`).join('')+`<div class="card"><b id="tsc">Acertos: ${trScore(i)}/${x.q.length}</b><p class="mut">Pontuação apenas educacional. Não indica desempenho financeiro.</p></div>`};
function tAns(i,n,k){const q=TREINOS[i].q[n],ok=k==q[2];S.tr[i]=S.tr[i]||{};S.tr[i][n]=S.tr[i][n]||ok;save();$('#tq'+n).innerHTML=`<p class="${ok?'pos':'neg'}"><b>${ok?'Correto!':'Incorreto. Resposta: '+q[1][q[2]]}</b></p><p>${q[3]}</p>`;$('#tsc').textContent=`Acertos: ${trScore(i)}/${TREINOS[i].q.length}`}
views.estrat=()=>`<a href="#aprender">← Aprender</a><h2>Estratégias (conceitos)</h2><p class="mut">Ideias hipotéticas para estudo. Nenhuma garante resultado.</p>`+ESTRAT.map(e=>`<details class="card"><summary><b>${e[0]}</b></summary>${['Contexto','Entrada hipotética','Stop','Alvo','Risco','O que invalida a ideia','Quando NÃO operar'].map((l,k)=>`<p><b>${l}:</b> ${e[k+1]}</p>`).join('')}</details>`).join('')+AVISO;
/* ===== v4: indicadores e biblioteca ===== */
views.indic=a=>{if(a===undefined)return`<a href="#aprender">← Aprender</a><h2>Indicadores</h2>`+INDIC.map((x,i)=>lnk('indic/'+i,`<b>${x[0]}</b><br><span class="mut">${x[1]}</span>`)).join('');
 const x=INDIC[+a];if(!x)return views.indic();return`<a href="#indic">← Indicadores</a><h2>${x[0]}</h2>${['O que é','Para que serve','Como interpretar','Erros comuns','Como combinar com outros elementos','Exemplo'].map((l,k)=>`<div class="card"><b>${l}</b><p>${x[k+1]}</p></div>`).join('')}<p class="mut">Indicador isolado não é garantia de entrada.</p>`+AVISO};
const BCAT=['Fundamentos','Gráficos','Indicadores','Gestão de risco','Psicologia','Estratégias','Cálculos','Glossário'];let bibCat=-1,bibQ='';
function bibItems(){const map={0:0,1:3,2:1,3:1,4:2,5:2,6:2,7:1,8:5,9:4},I=[];MODULOS.forEach((m,i)=>m.a.forEach((x,j)=>I.push([map[i],x[0],x[1],`aprender/${i}/${j}`])));
 INDIC.forEach((x,i)=>I.push([2,x[0]+' (indicador)',x[1]+' '+x[2],'indic/'+i]));ESTRAT.forEach(e=>I.push([5,'Estratégia: '+e[0],e[1],'estrat']));
 [['Calculadora de futuros','PnL, taxas, funding e liquidação estimada.','calc'],['Calculadora de alavancagem','Efeito de ±1%, 5% e 10% sobre a margem.','calc/alav'],['Risco e tamanho da posição','Quantidade a partir do risco e do stop.','calc/risco'],['USD ⇄ BRL','Conversor com cotação manual.','calc/cambio'],['Preço médio, take profit, impacto da perda, liquidação','Calculadoras complementares.','calc/mais']].forEach(x=>I.push([6,x[0],x[1],x[2]]));
 GLOS.forEach(g=>I.push([7,g[0],g[1],null]));return I}
views.biblio=()=>`<a href="#aprender">← Aprender</a><h2>📚 Biblioteca</h2><input id="bq" placeholder="Buscar…" value="${bibQ}" oninput="bibQ=this.value;bib()"><div class="tabs" style="margin-top:8px"><button class="btn ${bibCat<0?'':'alt'}" onclick="bibC(-1)">Todos</button>${BCAT.map((c,i)=>`<button class="btn ${bibCat==i?'':'alt'}" onclick="bibC(${i})">${c}</button>`).join('')}</div><div id="bl"></div>`;
function bibC(i){bibCat=i;render()}
function bib(){const q=bibQ.toLowerCase(),r=bibItems().filter(x=>(bibCat<0||x[0]==bibCat)&&(x[1]+' '+x[2]).toLowerCase().includes(q));$('#bl').innerHTML=r.slice(0,60).map(x=>{const b=`<b>${x[1]}</b><br><span class="mut">${x[2].slice(0,110)}${x[2].length>110?'…':''}</span>`;return x[3]?lnk(x[3],b):`<div class="card">${b}</div>`}).join('')||'<p class="mut">Nada encontrado.</p>'}
addEventListener('hashchange',render);render();
