const $=s=>document.querySelector(s),app=$('#app');
const V=id=>{const e=document.getElementById(id);return e?e.value:''};
const F=(id,l,v='',t='number')=>`<label>${l}</label><input id="${id}" type="${t}" inputmode="${t=='number'?'decimal':'text'}" step="any" value="${v}">`;
const R=(l,v,c='')=>`<div class="row"><span>${l}</span><b class="${c}">${v}</b></div>`;
const AVISO='<div class="card warn"><b>ATENÇÃO AO RISCO</b><p class="mut">Conteúdo educacional; nenhuma estratégia garante lucro. Alavancagem aumenta exposição e perdas podem ser rápidas. Stop não elimina todos os riscos. Liquidação pode ocorrer. Taxas, funding e slippage reduzem o resultado. Resultados passados não garantem resultados futuros.</p></div>';
document.documentElement.dataset.theme=S.cfg.theme;
const prog=()=>{const m=MODULOS.filter((_,i)=>modFrac([i])==1).length,q=Object.keys(S.quiz).length,c=Object.values(S.check).filter(x=>x===true).length;return{m,q,c,qp:Math.round(Object.values(S.quiz).filter(x=>x).length/QUIZ.length*100)}};
const bar=p=>`<div class="bar"><i style="width:${p}%"></i></div>`;
const stats=()=>{const t=S.trades,n=t.length,w=t.filter(x=>x.net>0),l=t.filter(x=>x.net<0),sum=k=>t.reduce((a,x)=>a+(x[k]||0),0);
 let sw=0,sl=0,mw=0,ml=0;t.forEach(x=>{if(x.net>0){sw++;sl=0}else if(x.net<0){sl++;sw=0}mw=Math.max(mw,sw);ml=Math.max(ml,sl)});
 const grp=k=>{const o={};t.forEach(x=>o[x[k]||'—']=(o[x[k]||'—']||0)+(x.net||0));return o};
 return{n,w:w.length,l:l.length,rate:n?w.length/n*100:NaN,bruto:sum('bruto'),taxas:sum('taxas'),fund:sum('fund'),net:sum('net'),max:Math.max(0,...t.map(x=>x.net||0)),min:Math.min(0,...t.map(x=>x.net||0)),mg:w.length?w.reduce((a,x)=>a+x.net,0)/w.length:0,mp:l.length?l.reduce((a,x)=>a+x.net,0)/l.length:0,mw,ml,ativo:grp('ativo'),tf:grp('tf'),side:grp('side')}};
const grpHTML=o=>Object.entries(o).map(([k,v])=>R(k,money(v),cls(v))).join('')||'<p class="mut">Sem dados.</p>';

const views={
inicio(){if(!S.welcomed)return`<div class="card"><h2>Bem-vindo ao Futures Trader Academy</h2><p>Aprenda primeiro. Simule depois. Registre suas operações. Só então considere operar com dinheiro real.</p><button class="btn" onclick="S.welcomed=true;save();go('aprender')">Começar aprendizado</button></div>`+AVISO;
 const p=prog(),s=stats(),u=S.trades[S.trades.length-1];
 return`<h2>Central de Trading</h2><div class="card"><b>Seu progresso</b>${bar(p.m/MODULOS.length*100)}<p class="mut">Módulos: ${p.m}/${MODULOS.length} · Checklist: ${p.c}/${CHECK.length} · Quiz: ${p.qp}% · Simulações: ${S.sims} · Operações: ${s.n}</p></div>
 <div class="grid"><div class="card"><span class="mut">Resultado do diário</span><div class="kpi ${cls(s.net)}">${money(s.net)}</div></div><div class="card"><span class="mut">Taxa de acerto</span><div class="kpi">${pct(s.rate)}</div></div></div>
 <div class="card"><span class="mut">Última operação</span><div>${u?`${u.data||''} · ${u.ativo||''} ${u.side||''} · <b class="${cls(u.net)}">${money(u.net)}</b>`:'Nenhuma registrada'}</div></div>
 <a class="btn" href="#aprender">Começar estudo</a><a class="btn alt" href="#analisar">Checklist de operação</a><a class="btn alt" href="#calc">Calculadoras</a><a class="btn alt" href="#diario">Diário de operações</a>`+AVISO},
aprender(a){if(a){const i=+a,m=MODULOS[i];return`<a href="#aprender">← Módulos</a><h2>${m.t}</h2>${m.b.map(x=>`<div class="card">${x}</div>`).join('')}<button class="btn ${S.done[i]?'ok':''}" onclick="S.done[${i}]=!S.done[${i}];if(!S.done[${i}])delete S.done[${i}];save();render()">${S.done[i]?'✓ Concluído':'Marcar como concluído'}</button>`+AVISO}
 return`<h2>Aprender</h2>${MODULOS.map((m,i)=>`<a class="card" style="display:block;text-decoration:none;color:inherit" href="#aprender/${i}"><b>${S.done[i]?'✅':'▫️'} ${m.t}</b></a>`).join('')}<a class="btn alt" href="#quiz">Fazer quiz (${prog().qp}%)</a>`},
quiz(a){const i=+a||0;if(i>=QUIZ.length)return`<div class="card"><h2>Quiz concluído</h2><p>Acertos: ${prog().qp}%</p><button class="btn" onclick="S.quiz={};save();go('quiz/0')">Refazer</button></div>`;
 const q=QUIZ[i];return`<h2>Quiz ${i+1}/${QUIZ.length}</h2>${bar(i/QUIZ.length*100)}<div class="card"><b>${q[0]}</b>${q[1].map((o,k)=>`<button class="btn alt opt" onclick="ans(${i},${k})">${o}</button>`).join('')}<div id="fb"></div></div>`},
analisar(a){const t=`<div class="tabs"><a class="btn ${!a?'':'alt'}" href="#analisar">Checklist</a><a class="btn ${a=='tec'?'':'alt'}" href="#analisar/tec">Análise técnica</a><a class="btn ${a=='sim'?'':'alt'}" href="#analisar/sim">Simulador</a></div>`;
 if(a=='tec')return t+`<div class="card"><h3>Análise técnica</h3><p>Monte sua própria leitura: contexto (tendência), estrutura (suporte, resistência, topos, fundos), confirmação (médias, volume, RSI, MACD) e cenário. Indicadores nem sempre concordam e não precisam estar todos ativos.</p><p class="mut">Cenários possíveis: alta, baixa ou espera. Nunca são certeza.</p><a class="btn" href="#aprender">Revisar módulos</a></div>`;
 if(a=='sim')return t+`<div class="card"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b>${F('s_b','Banca fictícia',1000)}<label>Long/Short</label><select id="s_s"><option value="long">Long</option><option value="short">Short</option></select>${F('s_e','Entrada',100)}${F('s_x','Saída',105)}${F('s_l','Alavancagem',10)}${F('s_st','Stop Loss (opcional)')}${F('s_tp','Take Profit (opcional)')}${F('s_m','Margem usada',100)}<button class="btn" onclick="sim()">Simular</button><div id="s_o"></div></div>`;
 const c=S.check,val=k=>c[k]||'';
 return t+`<div class="card"><h3>Checklist pré-operação</h3>${F('c_ativo','1. Ativo',val('ativo'),'text')}${F('c_tf','Timeframe principal',val('tf'),'text')}<label>Tendência</label><select id="c_tr">${['Alta','Baixa','Lateral'].map(x=>`<option ${val('tr')==x?'selected':''}>${x}</option>`).join('')}</select>
 <p class="mut">2–3. Estrutura e indicadores</p>${CHECK.map((x,i)=>`<label style="color:var(--tx)"><input type="checkbox" style="width:auto;min-height:0" ${c['k'+i]?'checked':''} onchange="S.check.k${i}=this.checked;save()"> ${x}</label>`).join('')}
 <label>4. Hipótese</label><select id="c_h">${['LONG','SHORT','NÃO OPERAR'].map(x=>`<option ${val('h')==x?'selected':''}>${x}</option>`).join('')}</select><label>Justificativa</label><textarea id="c_j">${val('j')}</textarea>
 ${F('c_e','5. Preço de entrada',val('e'))}${F('c_s','6. Preço do stop',val('s'))}${F('c_p','Valor máximo que aceita perder',val('p'))}${F('c_t','7. Preço alvo',val('t'))}<button class="btn alt" onclick="chk()">Calcular e concluir</button><div id="c_o"></div></div>`},
calc(a){const t=`<div class="tabs">${[['','Futuros'],['alav','Alavancagem'],['risco','Risco'],['cambio','USD⇄BRL'],['mais','Mais']].map(([k,n])=>`<a class="btn ${a==k||(!a&&!k)?'':'alt'}" href="#calc${k?'/'+k:''}">${n}</a>`).join('')}</div>`;
 const ipt=(ids)=>`oninput="${ids}()"`;
 if(a=='alav')return t+`<div class="card"><b>Calculadora de alavancagem</b>${F('a_m','Margem',20).replace('<input','<input oninput="calcA()"')}${F('a_l','Alavancagem (x)',10).replace('<input','<input oninput="calcA()"')}<div id="a_o"></div><p class="mut">Aproximação antes de taxas, funding e slippage. 10x não significa ganhar 10 vezes o dinheiro.</p></div>`;
 if(a=='risco')return t+`<div class="card"><b>Risco e tamanho da posição</b>${['r_b|Banca|'+(S.bank.cur||1000),'r_r|Risco máximo (%)|'+(S.bank.risco||1),'r_e|Entrada|100','r_s|Stop Loss|98','r_l|Alavancagem|5'].map(x=>{const[i,l,v]=x.split('|');return F(i,l,v).replace('<input','<input oninput="calcR()"')}).join('')}<div id="r_o"></div></div>`;
 if(a=='cambio')return t+`<div class="card"><b>Conversor</b>${F('f_v','Valor',20).replace('<input','<input oninput="calcF()"')}${F('f_c','Cotação usada (R$ por US$)',S.cfg.fx).replace('<input','<input oninput="calcF()"')}<label>Direção</label><select id="f_d" onchange="calcF()"><option value="u">USD → BRL</option><option value="b">BRL → USD</option></select><div id="f_o"></div></div>`;
 return t+`<div class="card"><b>Calculadora de Futuros (modelo genérico)</b>${F('k_a','Ativo','BTCUSDT','text')}<label>Long/Short</label><select id="k_s" onchange="calcK()"><option value="long">Long</option><option value="short">Short</option></select>${[['k_m','Margem',20],['k_l','Alavancagem',10],['k_e','Preço de entrada',100],['k_x','Preço de saída',105],['k_sl','Stop Loss',''],['k_tp','Take Profit',''],['k_fe','Taxa de entrada (%)',0.05],['k_fs','Taxa de saída (%)',0.05],['k_fu','Funding (%)',0]].map(([i,l,v])=>F(i,l,v).replace('<input','<input oninput="calcK()"')).join('')}<div id="k_o"></div><p class="mut">ESTIMATIVA EDUCACIONAL. O preço real de liquidação depende da corretora, contrato, margem, modo de margem, taxas, funding e regras específicas da plataforma.</p></div>`},
diario(a){const s=stats();const fld=[['d_data','Data',new Date().toISOString().slice(0,10),'date'],['d_hora','Hora',new Date().toTimeString().slice(0,5),'time'],['d_ativo','Ativo','','text'],['d_tf','Timeframe','','text'],['d_e','Preço de entrada'],['d_x','Preço de saída'],['d_m','Margem'],['d_l','Alavancagem'],['d_st','Stop'],['d_tp','Take Profit'],['d_taxas','Taxas'],['d_fund','Funding'],['d_risco','Risco ($)']];
 return`<h2>Meu Diário</h2><div class="tabs"><a class="btn ${a?'alt':''}" href="#diario">Novo</a><a class="btn ${a=='hist'?'':'alt'}" href="#diario/hist">Histórico</a><a class="btn ${a=='est'?'':'alt'}" href="#diario/est">Estatísticas</a><a class="btn ${a=='banca'?'':'alt'}" href="#diario/banca">Banca</a></div>`+
 (a=='hist'?`<div class="card tbl"><table><tr><th>Data</th><th>Ativo</th><th>L/S</th><th>Líquido</th><th></th></tr>${S.trades.slice().reverse().map((x,i)=>`<tr><td>${x.data||''}</td><td>${x.ativo||''}</td><td>${x.side||''}</td><td class="${cls(x.net)}">${money(x.net)}</td><td><button onclick="go('diario/edit/${S.trades.length-1-i}')">✏️</button> <button onclick="go('diario/rev/${S.trades.length-1-i}')">📝</button> <button onclick="delT(${S.trades.length-1-i})">🗑</button></td></tr>`).join('')}</table></div><button class="btn alt" onclick="exportCSV()">Exportar CSV</button>`
 :a=='est'?`<div class="card">${R('Total de operações',s.n)}${R('Positivas / Negativas',s.w+' / '+s.l)}${R('Taxa de acerto',pct(s.rate))}${R('Resultado bruto',money(s.bruto),cls(s.bruto))}${R('Taxas',money(s.taxas))}${R('Funding',money(s.fund))}${R('Resultado líquido',money(s.net),cls(s.net))}${R('Maior ganho',money(s.max))}${R('Maior perda',money(s.min))}${R('Média de ganho',money(s.mg))}${R('Média de perda',money(s.mp))}${R('Sequência de ganhos / perdas',s.mw+' / '+s.ml)}</div><div class="card"><b>Por ativo</b>${grpHTML(s.ativo)}<b>Por timeframe</b>${grpHTML(s.tf)}<b>Long / Short</b>${grpHTML(s.side)}</div><div class="card"><b>Resultado por operação</b><div class="hb">${S.trades.map(x=>`<i title="${money(x.net)}" style="height:${Math.max(4,Math.abs(x.net||0)/(Math.max(s.max,-s.min)||1)*100)}%;background:${x.net>=0?'var(--ok)':'var(--bad)'}"></i>`).join('')}</div></div><p class="mut">Estatísticas descritivas; não indicam desempenho futuro.</p>`
 :a=='banca'?bancaHTML()
 :`<div class="card"><label>Long/Short</label><select id="d_side"><option value="long">Long</option><option value="short">Short</option></select>${fld.map(([i,l,v,t])=>F(i,l,v||'',t||'number')).join('')}<p class="mut">Se deixar em branco, o resultado bruto é estimado por entrada/saída/margem/alavancagem.</p>${F('d_bruto','Resultado bruto (opcional)')}${[['d_why','Motivo da entrada'],['d_est','Estratégia utilizada'],['d_eb','Emoção antes da entrada'],['d_ea','Emoção depois da saída'],['d_ok','O que fiz certo?'],['d_no','O que fiz errado?'],['d_ap','O que aprendi?'],['d_nota','Print/anotação']].map(([i,l])=>`<label>${l}</label><textarea id="${i}"></textarea>`).join('')}<button class="btn" onclick="addT()">Salvar operação</button></div>`)},
config(){return`<h2>Configurações</h2><div class="card"><label>Tema</label><select onchange="S.cfg.theme=this.value;save();document.documentElement.dataset.theme=this.value"><option value="dark" ${S.cfg.theme=='dark'?'selected':''}>Escuro</option><option value="light" ${S.cfg.theme=='light'?'selected':''}>Claro</option></select><label>Moeda padrão</label><select onchange="S.cfg.moeda=this.value;save()"><option ${S.cfg.moeda=='USD'?'selected':''}>USD</option><option ${S.cfg.moeda=='BRL'?'selected':''}>BRL</option></select>${F('cfg_fx','Cotação USD/BRL',S.cfg.fx).replace('<input','<input onchange="S.cfg.fx=N(this.value)||5.5;save()"')}</div><button class="btn" onclick="exportJSON()">Exportar dados (JSON)</button><button class="btn alt" onclick="exportCSV()">Exportar diário (CSV)</button><label class="btn alt">Importar dados (JSON)<input type="file" accept=".json" hidden onchange="importJSON(this.files[0])"></label><button class="btn alt" style="color:var(--bad)" onclick="if(confirm('Apagar todos os dados?')){localStorage.removeItem(KEY);location.reload()}">Limpar dados</button>`+AVISO}};
function bancaHTML(){const b=S.bank,net=stats().net,cur=(b.cur||b.ini||0),v=b.ini?(cur-b.ini)/b.ini*100:NaN;
 return`<div class="card">${[['b_i','Banca inicial',b.ini],['b_c','Banca atual',b.cur],['b_me','Meta diária (opcional)',b.meta],['b_li','Limite diário de perda',b.lim],['b_r','Risco por operação (%)',b.risco]].map(([i,l,v])=>F(i,l,v||'')).join('')}<button class="btn" onclick="saveBanca()">Salvar banca</button>${R('Lucro/prejuízo',money(cur-b.ini),cls(cur-b.ini))}${R('Variação',pct(v))}${R('Resultado do diário',money(net),cls(net))}<b>Evolução</b><div class="hb">${b.hist.map(h=>`<i title="${h.v}" style="height:${Math.max(4,h.v/(Math.max(...b.hist.map(x=>x.v))||1)*100)}%"></i>`).join('')}</div></div>`}
function saveBanca(){const b=S.bank;b.ini=N(V('b_i'))||0;b.cur=N(V('b_c'))||0;b.meta=N(V('b_me'))||0;b.lim=N(V('b_li'))||0;b.risco=N(V('b_r'))||1;if(b.cur)b.hist.push({d:new Date().toISOString().slice(0,10),v:b.cur});save();render()}
function addT(){const g=N(V('d_e')),m=N(V('d_m')),l=N(V('d_l')),x=N(V('d_x')),side=V('d_side');let bruto=N(V('d_bruto'));
 if(!isFinite(bruto)){const r=calcFut({margem:m,lev:l,entrada:g,saida:x,side});bruto=r?r.bruto:0}
 const taxas=N(V('d_taxas'))||0,fund=N(V('d_fund'))||0;
 S.trades.push({data:V('d_data'),hora:V('d_hora'),ativo:V('d_ativo').toUpperCase(),side,tf:V('d_tf'),entrada:g,saida:x,margem:m,lev:l,stop:N(V('d_st')),tp:N(V('d_tp')),bruto,taxas,fund,net:bruto-taxas-fund,risco:N(V('d_risco'))||0,nota:V('d_nota'),motivo:V('d_why'),estrategia:V('d_est'),emoAntes:V('d_eb'),emoDepois:V('d_ea'),certo:V('d_ok'),errado:V('d_no'),aprendi:V('d_ap')});save();go('diario/rev/'+(S.trades.length-1))}
function delT(i){if(confirm('Excluir operação?')){S.trades.splice(i,1);save();render()}}
function ans(i,k){const q=QUIZ[i],ok=k==q[2];S.quiz[i]=ok;save();$('#fb').innerHTML=`<p class="${ok?'pos':'neg'}"><b>${ok?'Correto!':'Incorreto. Resposta: '+q[1][q[2]]}</b></p><p>${q[3]}</p><a class="btn" href="#quiz/${i+1}">Próxima</a>`}
function chk(){const c=S.check;c.ativo=V('c_ativo');c.tf=V('c_tf');c.tr=V('c_tr');c.h=V('c_h');c.j=V('c_j');c.e=V('c_e');c.s=V('c_s');c.p=V('c_p');c.t=V('c_t');save();
 const rr=calcRR(N(c.e),N(c.s),N(c.t));$('#c_o').innerHTML=(rr?R('Risco (por unidade)',rr.risco.toFixed(4))+R('Retorno potencial',rr.ret.toFixed(4))+R('Risco/retorno','1 : '+rr.rr.toFixed(2)):'<p class="mut">Preencha entrada, stop e alvo para calcular.</p>')+`<div class="card"><b>Checklist concluído.</b><p>Você definiu um cenário. Agora revise os riscos antes de executar.</p><button class="btn" onclick="regChk()">Registrar operação</button></div>`}
function regChk(){const c=S.check;S.trades.push({data:new Date().toISOString().slice(0,10),ativo:(c.ativo||'').toUpperCase(),side:c.h=='SHORT'?'short':'long',tf:c.tf,entrada:N(c.e),stop:N(c.s),tp:N(c.t),bruto:0,taxas:0,fund:0,net:0,motivo:c.j});save();go('diario/hist')}
function sim(){const r=calcFut({margem:N(V('s_m')),lev:N(V('s_l')),entrada:N(V('s_e')),saida:N(V('s_x')),side:V('s_s'),fe:0.05,fs:0.05});if(!r)return $('#s_o').innerHTML='<p class="neg">Valores inválidos.</p>';S.sims++;save();
 $('#s_o').innerHTML=R('Posição',money(r.pos,'USD'))+R('Variação',pct(r.var_))+R('Resultado líquido (taxas 0,05%+0,05%)',money(r.liq,'USD'),cls(r.liq))+R('Banca fictícia final',money(N(V('s_b'))+r.liq,'USD'))+R('Liquidação aprox.',money(r.liqPx,'USD'))+'<p class="mut"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b></p>'}
function calcK(){const r=calcFut({margem:N(V('k_m')),lev:N(V('k_l')),entrada:N(V('k_e')),saida:N(V('k_x')),side:V('k_s'),fe:N(V('k_fe'))||0,fs:N(V('k_fs'))||0,fund:N(V('k_fu'))||0});
 $('#k_o').innerHTML=r?R('Valor da posição',money(r.pos,'USD'))+R('Quantidade',(r.pos/N(V('k_e'))).toFixed(6))+R('Variação do ativo (lado)',pct(r.var_))+R('PnL bruto',money(r.bruto,'USD'),cls(r.bruto))+R('Taxas estimadas',money(r.taxas,'USD'))+R('Funding estimado',money(r.fundv,'USD'))+R('PnL líquido estimado',money(r.liq,'USD'),cls(r.liq))+R('Retorno sobre a margem',pct(r.roi),cls(r.roi))+R('Liquidação (aprox., genérico)',money(r.liqPx,'USD')):'<p class="mut">Informe margem, alavancagem ≥ 1 e entrada > 0.</p>'}
function calcA(){const m=N(V('a_m')),l=N(V('a_l'));if(!(m>0&&l>=1))return $('#a_o').innerHTML='<p class="mut">Valores inválidos.</p>';
 $('#a_o').innerHTML=R('MARGEM',money(m,'USD'))+R('VALOR DA POSIÇÃO',money(m*l,'USD'))+[1,5,10,-1,-5,-10].map(p=>R('Ativo '+(p>0?'+':'')+p+'%','PnL bruto ≈ '+money(m*l*p/100,'USD'),cls(p))).join('')}
function calcR(){const r=calcRisco({banca:N(V('r_b')),r:N(V('r_r')),entrada:N(V('r_e')),stop:N(V('r_s')),lev:N(V('r_l'))});
 $('#r_o').innerHTML=r?R('Risco máximo em dinheiro',money(r.rd,'USD'))+R('Distância até o stop',r.dist.toFixed(4)+' ('+pct(r.distP)+')')+R('Tamanho estimado da posição',money(r.pos,'USD'))+R('Quantidade',r.qtd.toFixed(6))+R('Margem necessária',money(r.margem,'USD'))+`<p class="mut">Cálculo: risco ($) ÷ distância até o stop = quantidade; quantidade × entrada = posição. A margem não é o risco: o risco é o que você perde se o stop for atingido.${r.pctBanca>100*N(V('r_l'))?'':''}</p>`:'<p class="mut">Informe valores válidos (entrada ≠ stop).</p>'}
function calcF(){const v=N(V('f_v')),c=N(V('f_c'));$('#f_o').innerHTML=v>=0&&c>0?R('Resultado',V('f_d')=='u'?money(v*c,'BRL'):money(v/c,'USD')):'<p class="mut">Valores inválidos.</p>'}
function go(h){location.hash=h}
function render(){const[h,a,b]=(location.hash.slice(1)||'inicio').split('/'),v=views[h]||views.inicio;app.innerHTML=v(a,b);document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('on',x.getAttribute('href')=='#'+(({quiz:'aprender',treino:'aprender',biblio:'aprender',indic:'aprender',estrat:'aprender',plano:'aprender',gloss:'aprender',nao:'analisar',riscos:'inicio'})[h]||h)));scrollTo(0,0);
 ({biblio:()=>bib(),gloss:()=>gl(),calc:()=>({undefined:calcK,alav:calcA,risco:calcR,cambio:calcF,mais:calcM}[a]||calcK)()})[h]?.()}
/* ===== v2: academia guiada ===== */
const LESS=[];MODULOS.forEach((m,i)=>m.a.forEach((_,j)=>LESS.push([i,j])));
const ad=(i,j)=>S.aulas[i+'.'+j];
const modFrac=ms=>{let t=0,d=0;ms.forEach(i=>MODULOS[i].a.forEach((_,j)=>{t++;if(ad(i,j))d++}));return t?d/t:0};
const nextLesson=ms=>{for(const i of ms)for(let j=0;j<MODULOS[i].a.length;j++)if(!ad(i,j))return[i,j]};
const ETAPAS=[['Fundamentos','Entenda futuros, margem e liquidação.',()=>modFrac([0]),[0]],['Gráficos','Candles, suporte/resistência e estrutura.',()=>modFrac([2,3,7]),[2,3,7]],['Indicadores','Médias, volume, RSI e MACD.',()=>modFrac([4,5,6]),[4,5,6]],['Gestão de risco','Alavancagem, stop e risco por operação.',()=>modFrac([1]),[1]],['Estratégia','Estratégias e psicologia.',()=>modFrac([8,9]),[8,9]],['Simulação','Salve 5 simulações.',()=>Math.min(1,S.simsList.length/5),0,'analisar/sim'],['Checklist de operação','Conclua o checklist guiado.',()=>S.checkDone?1:0,0,'analisar'],['Diário','Registre 3 operações.',()=>Math.min(1,S.trades.length/3),0,'diario'],['Revisão de desempenho','Faça 1 revisão pós-operação.',()=>Math.min(1,S.revs),0,'diario/hist'],['Preparação para operação real','Leia os riscos e confirme seus limites.',()=>S.prep?1:0,0,'riscos']];
const etHref=e=>{const nl=e[3]&&nextLesson(e[3]);return nl?`aprender/${nl[0]}/${nl[1]}`:e[3]?'aprender/'+e[3][0]:e[4]};
views.inicio=()=>{const fr=ETAPAS.map(e=>e[2]()),n=fr.filter(x=>x>=1).length,k=fr.findIndex(x=>x<1),s=stats(),p=prog(),nx=ETAPAS[k],nl=nx&&nx[3]?nextLesson(nx[3]):null;
 const txt=k<0?'Você concluiu as 10 etapas. Continue registrando e revisando.':`Você concluiu ${n} de 10 etapas.<br><b>Próximo passo:</b> ${nl?'aprender "'+MODULOS[nl[0]].a[nl[1]][0]+'"':nx[0]+' — '+nx[1]}`;
 return`<h2>Bem-vindo à Futures Trader Academy</h2><p class="mut">Antes de pensar em operar, aprenda a analisar, controlar o risco e montar um plano.</p>
 <div class="card"><b>SEU CAMINHO DE APRENDIZADO</b><p>${txt}</p><a class="btn" href="#${k<0?'diario':etHref(nx)}">CONTINUAR MEU ESTUDO</a></div>
 <div class="grid"><div class="card"><span class="mut">Módulos</span><div class="kpi">${p.m}/${MODULOS.length}</div></div><div class="card"><span class="mut">Aulas</span><div class="kpi">${Object.keys(S.aulas).length}/${LESS.length}</div></div><div class="card"><span class="mut">Quizzes</span><div class="kpi">${Object.values(S.mq).filter(Boolean).length}/${MODULOS.length}</div></div><div class="card"><span class="mut">Simulações</span><div class="kpi">${S.simsList.length}</div></div><div class="card"><span class="mut">Operações</span><div class="kpi">${s.n}</div></div></div>
 <div class="grid"><a class="btn alt" href="#analisar">✅ Checklist</a><a class="btn alt" href="#analisar/sim">🧪 Simulador</a><a class="btn alt" href="#plano">📅 Plano</a><a class="btn alt" href="#diario">📝 Diário</a></div>
 ${ETAPAS.map((e,i)=>{const f=fr[i];return`<div class="card step ${f>=1?'ok':''}"><b>${f>=1?'✅':i==k?'👉':'▫️'} Etapa ${i+1} — ${e[0]}</b><p class="mut">${e[1]}${i?'<br>Pré-requisito: etapa '+i+' ('+ETAPAS[i-1][0]+')':''}</p>${bar(Math.round(f*100))}<a class="btn alt" href="#${etHref(e)}">Continuar</a></div>`}).join('')}<a class="btn alt" href="#treino">🎯 Modo Treinamento</a><a class="btn alt" href="#riscos">⚠️ Riscos do mercado futuro</a>`+AVISO};
const lnk=(h,t)=>`<a class="card" style="display:block;text-decoration:none;color:inherit" href="#${h}">${t}</a>`;
views.aprender=(a,b)=>{if(a===undefined)return`<h2>Aprender</h2>${MODULOS.map((m,i)=>{const f=modFrac([i]);return lnk('aprender/'+i,`<b>${f>=1?'✅':'▫️'} ${m.t}</b>${bar(Math.round(f*100))}`)}).join('')}<div class="grid"><a class="btn alt" href="#plano">📅 Plano de estudos</a><a class="btn alt" href="#biblio">📚 Biblioteca</a><a class="btn alt" href="#indic">📈 Indicadores</a><a class="btn alt" href="#treino">🎯 Modo Treinamento</a><a class="btn alt" href="#estrat">♟️ Estratégias</a><a class="btn alt" href="#gloss">📝 Glossário</a><a class="btn alt" href="#nao">⛔ Quando não operar</a><a class="btn alt" href="#quiz">🎯 Quiz geral (${prog().qp}%)</a></div>`;
 const i=+a,m=MODULOS[i];if(!m)return views.aprender();
 if(b!==undefined){const j=+b,x=m.a[j];if(!x)return views.aprender(a);return`<a href="#aprender/${i}">← ${m.t}</a><h2>${x[0]}</h2><div class="card">${x[1]}</div>${lessonExtra(i,j)}<button class="btn ok" onclick="fim(${i},${j})">${ad(i,j)?'Aula concluída · continuar':'Concluir aula'}</button>`+AVISO}
 return`<a href="#aprender">← Módulos</a><h2>${m.t}</h2>${m.a.map((x,j)=>lnk(`aprender/${i}/${j}`,(ad(i,j)?'✅ ':'▫️ ')+x[0])).join('')}<div class="card"><b>Quiz do módulo</b> ${S.mq[i]?'✅':''}<p>${m.q[0]}</p>${m.q[1].map((o,k)=>`<button class="btn alt opt" onclick="mAns(${i},${k})">${o}</button>`).join('')}<div id="fb"></div></div>`};
function fim(i,j){S.aulas[i+'.'+j]=true;save();go(j+1<MODULOS[i].a.length?`aprender/${i}/${j+1}`:`aprender/${i}`)}
function mAns(i,k){const q=MODULOS[i].q,ok=k==q[2];S.mq[i]=S.mq[i]||ok;save();$('#fb').innerHTML=`<p class="${ok?'pos':'neg'}"><b>${ok?'Correto!':'Incorreto.'}</b> ${q[3]}</p><button class="btn alt" onclick="render()">Tentar novamente</button>`}
views.plano=()=>{const n=S.plano.n,per=Math.ceil(LESS.length/n);return`<a href="#aprender">← Aprender</a><h2>Meu Plano de Estudos</h2><label>Duração (dias)</label><select onchange="S.plano.n=+this.value;save();render()">${[7,14,30].map(x=>`<option ${x==n?'selected':''}>${x}</option>`).join('')}</select>`+Array.from({length:n},(_,d)=>{const L=LESS.slice(d*per,d*per+per);return`<div class="card"><label style="color:var(--tx)"><input type="checkbox" style="width:auto;min-height:0" ${S.plano.done[d]?'checked':''} onchange="S.plano.done[${d}]=this.checked;save()"> <b>DIA ${d+1}</b></label><p>📖 ${L.length?L.map(([i,j])=>`<a href="#aprender/${i}/${j}">${MODULOS[i].a[j][0]}</a>`).join(', '):'Revisão geral dos módulos e do diário'}</p><p class="mut">Leitura: glossário · Exercício: explique a aula com suas palavras · Quiz do módulo · 1 simulação · Revisão</p></div>`}).join('')};
views.gloss=()=>`<a href="#aprender">← Aprender</a><h2>Glossário</h2><input id="gq" placeholder="Buscar termo…" oninput="gl()"><div id="gl"></div>`;
function gl(){const q=(V('gq')||'').toLowerCase();$('#gl').innerHTML=GLOS.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q)).map(x=>`<div class="card"><b>${x[0]}</b><br>${x[1]}</div>`).join('')||'<p class="mut">Nada encontrado.</p>'}
views.nao=()=>`<a href="#analisar">← Analisar</a><h2>QUANDO NÃO OPERAR</h2><div class="card">${['Mercado sem direção','Entrada sem stop definido','Risco acima do limite','Tentativa de recuperar prejuízo','Operação baseada em emoção','Entrada após movimento exagerado','Falta de confluência','Você não sabe explicar o motivo da operação','Tamanho da posição incompatível com a banca'].map(x=>`<p>⛔ ${x}</p>`).join('')}<p><b>Não operar também é uma decisão válida.</b></p></div>`;
views.riscos=()=>{const ok=ETAPAS.slice(0,9).every(e=>e[2]()>=1);return`<h2>RISCOS DO MERCADO FUTURO</h2><div class="card">${['Perdas podem ocorrer rapidamente.','Alavancagem aumenta a exposição.','Liquidação pode ocorrer.','Stop não elimina todos os riscos.','O preço pode sofrer movimentos bruscos.','Taxas e funding impactam os resultados.','Dados de mercado podem variar entre corretoras.','Resultados passados não garantem resultados futuros.'].map(x=>`<p>• ${x}</p>`).join('')}<p><b>Este aplicativo é exclusivamente educacional e não constitui recomendação financeira.</b></p></div>${S.prep?'<p class="pos">Etapa 10 concluída.</p>':ok?'<button class="btn ok" onclick="S.prep=true;save();render()">Li e entendi os riscos</button>':'<p class="mut">Conclua as etapas 1–9 para liberar a etapa 10.</p>'}`};
/* checklist guiado */
const WZ=[['Contexto',[['ativo','Qual ativo estou analisando?','t'],['tf','Qual timeframe?','t'],['tend','Tendência ou lateralização?','s:Tendência de alta|Tendência de baixa|Lateralização'],['mov','Existe movimento claro?','y']]],['Estrutura',[['hh','Existe HH/HL?','y'],['lh','Existe LH/LL?','y'],['mud','Houve mudança de estrutura?','y'],['niv','Onde estão os principais níveis?','t']]],['Suporte e resistência',[['sup','Onde está o suporte?','n'],['res','Onde está a resistência?','n'],['prox','O preço está próximo de alguma zona importante?','y']]],['Médias',[['mm','Onde está a MM/EMA?','t'],['acima','O preço está acima ou abaixo?','s:Acima|Abaixo|Sobre a média'],['incl','As médias estão inclinadas?','y'],['cruz','Existe cruzamento?','y'],['alin','As médias estão alinhadas?','y']]],['Volume',[['vol','O volume está aumentando?','y'],['conf','O movimento possui confirmação de volume?','y'],['div','Existe divergência entre preço e volume?','y']]],['Confirmação',[['conflu','Existe confluência?','y'],['claro','O cenário está claro?','y'],['motivo','Existe motivo objetivo para a operação?','y'],['inval','O cenário está invalidado?','y']]],['Risco',[['perde','Quanto estou disposto a perder ($)?','n'],['stop','Onde fica o stop?','n'],['tam','Qual é o tamanho da posição?','n'],['lev','Qual é a alavancagem?','n'],['dentro','O risco está dentro do limite definido?','y']]],['Plano',[['p_ativo','Ativo','t'],['p_side','Long ou Short','s:Long|Short'],['p_e','Preço de entrada','n'],['p_sl','Stop Loss','n'],['p_tp','Take Profit','n'],['p_r','Risco em $','n'],['p_tam','Tamanho da posição','n'],['p_lev','Alavancagem','n'],['p_mot','Motivo da operação','t']]]];
function fld(k,l,t){const v=String(S.wz.d[k]??'').replace(/"/g,'&quot;'),on=`onchange="S.wz.d.${k}=this.value;save()"`;
 if(t=='y'||t[0]=='s')return`<label>${l}</label><select ${on}><option value=""></option>${(t=='y'?['Sim','Não']:t.slice(2).split('|')).map(x=>`<option ${v==x?'selected':''}>${x}</option>`).join('')}</select>`;
 return`<label>${l}</label><input ${on} type="${t=='n'?'number':'text'}" inputmode="${t=='n'?'decimal':'text'}" step="any" value="${v}">`}
function wzGo(n){S.wz.i=Math.max(0,Math.min(8,n));save();render()}
function wzView(){const i=S.wz.i;if(i>7)return wzFinal();const st=WZ[i];return`<div class="card"><b>CHECKLIST ANTES DA OPERAÇÃO</b><p class="mut">Etapa ${i+1} de 9 — ${st[0]}</p>${bar((i+1)/9*100)}${st[1].map(f=>fld(...f)).join('')}<div class="grid"><button class="btn alt" onclick="wzGo(${i-1})">← Anterior</button><button class="btn" onclick="wzGo(${i+1})">Próxima →</button></div><a href="#nao">Quando não operar?</a></div>`}
function wzFinal(){const d=S.wz.d,e=N(d.p_e),sl=N(d.p_sl),tp=N(d.p_tp),r=N(d.p_r),w=[],rr=calcRR(e,sl,tp),lim=(S.bank.cur||S.bank.ini||0)*(S.bank.rop||S.bank.risco||1)/100;
 if(!(sl>0)||sl===e)w.push('Stop não definido ou igual à entrada.');if(!d.p_mot)w.push('Motivo da operação não explicado.');if(d.inval=='Sim')w.push('Você indicou que o cenário está invalidado.');if(d.claro=='Não'||d.conflu=='Não'||d.motivo=='Não')w.push('Falta clareza, confluência ou motivo objetivo.');if(d.dentro=='Não'||(lim>0&&r>lim))w.push('Risco acima do limite definido.');if(rr&&rr.rr<1)w.push('Relação risco/retorno abaixo de 1:1.');
 const D={ok:'🟢 PLANO APROVADO PARA SIMULAÇÃO',espera:'🟡 AINDA PRECISA DE CONFIRMAÇÃO',nao:'🔴 NÃO OPERAR'};
 return`<div class="card"><b>Etapa 9 — Decisão final</b>${R('Ativo / lado',(d.p_ativo||'—')+' / '+(d.p_side||'—'))}${R('Entrada · Stop · Alvo',[e,sl,tp].map(x=>isFinite(x)?x:'—').join(' · '))}${R('Risco / retorno',rr?'1 : '+rr.rr.toFixed(2):'—')}${R('Risco em $',money(r,'USD'))}${w.length?`<p class="neg"><b>Pontos de atenção:</b></p>${w.map(x=>`<p>• ${x}</p>`).join('')}`:'<p class="mut">Nenhum ponto de atenção automático. Ainda assim, revise.</p>'}<p class="mut">O app não recomenda operações. A decisão final é sua:</p>${Object.entries(D).map(([k,v])=>`<button class="btn ${S.wz.dec==k?'':'alt'}" onclick="wzDec('${k}')">${v}</button>`).join('')}${S.wz.dec?`<p><b>Checklist concluído.</b> Você definiu um cenário. Agora revise os riscos antes de executar.</p>${S.wz.dec=='ok'?'<button class="btn" onclick="wzSim()">Simular este plano</button><button class="btn alt" onclick="wzReg()">Registrar operação</button>':''}`:''}<button class="btn alt" onclick="wzGo(7)">← Editar plano</button><button class="btn alt" onclick="S.wz={i:0,d:{}};save();render()">Novo checklist</button></div>`}
function wzDec(k){S.wz.dec=k;S.checkDone=true;save();render()}
function wzSim(){const d=S.wz.d;S.simPre={a:d.p_ativo,tf:d.tf,s:(d.p_side||'Long').toLowerCase(),e:d.p_e,sl:d.p_sl,tp:d.p_tp,l:d.p_lev};save();go('analisar/sim')}
function wzReg(){const d=S.wz.d;S.trades.push({data:new Date().toISOString().slice(0,10),ativo:(d.p_ativo||'').toUpperCase(),side:(d.p_side||'Long').toLowerCase(),tf:d.tf,entrada:N(d.p_e),stop:N(d.p_sl),tp:N(d.p_tp),risco:N(d.p_r)||0,lev:N(d.p_lev),bruto:0,taxas:0,fund:0,net:0,motivo:d.p_mot});save();go('diario/rev/'+(S.trades.length-1))}
views.analisar=a=>`<div class="tabs">${[['','Checklist'],['tec','Mapa'],['sim','Simulador']].map(([k,n])=>`<a class="btn ${(a||'')==k?'':'alt'}" href="#analisar${k?'/'+k:''}">${n}</a>`).join('')}<a class="btn alt" href="#nao">Não operar</a></div>`+(a=='tec'?mapaForm():a=='sim'?simForm():wzView());
/* mapa da análise */
function mapaForm(){const S_=(id,l,o)=>`<label>${l}</label><select id="${id}">${o.map(x=>`<option>${x}</option>`).join('')}</select>`;return`<div class="card"><b>Análise guiada</b>${F('m_a','Ativo','','text')}${F('m_tf','Timeframe','','text')}${F('m_p','Preço atual')}${S_('m_t','Tendência',['Alta','Baixa','Lateral'])}${F('m_s','Suporte')}${F('m_r','Resistência')}${S_('m_m','Preço vs médias',['Acima','Abaixo','Misto'])}${S_('m_v','Volume',['Crescente','Decrescente','Neutro'])}${F('m_rsi','RSI (0–100)')}${S_('m_ma','MACD',['Positivo','Negativo','Neutro'])}<label>Contexto</label><textarea id="m_c"></textarea><button class="btn" onclick="mapa()">Montar mapa da análise</button><div id="m_o"></div></div>`}
function mapa(){const p=N(V('m_p')),s=N(V('m_s')),r=N(V('m_r')),t=V('m_t'),m=V('m_m'),v=V('m_v'),rsi=N(V('m_rsi')),mc=V('m_ma');if(!(p>0))return $('#m_o').innerHTML='<p class="neg">Informe o preço atual.</p>';
 const up=t=='Alta'&&m=='Acima'&&mc=='Positivo',dn=t=='Baixa'&&m=='Abaixo'&&mc=='Negativo',c=[],at=[];
 if(t=='Alta'&&m=='Acima')c.push('Tendência de alta com preço acima das médias');if(t=='Baixa'&&m=='Abaixo')c.push('Tendência de baixa com preço abaixo das médias');if((t=='Alta'&&mc=='Positivo')||(t=='Baixa'&&mc=='Negativo'))c.push('MACD alinhado à tendência');if(v=='Crescente'&&t!='Lateral')c.push('Volume crescente acompanhando o movimento');
 if(t=='Lateral')at.push('Mercado sem direção clara');if(v=='Decrescente')at.push('Volume caindo: risco de falso rompimento');if(rsi>=70)at.push('RSI esticado para cima');if(rsi<=30)at.push('RSI esticado para baixo');if(m=='Misto')at.push('Médias sem alinhamento');if(s>0&&Math.abs(p-s)/p<.01)at.push('Preço próximo do suporte');if(r>0&&Math.abs(r-p)/p<.01)at.push('Preço próximo da resistência');
 const rs=r>0?r:'a resistência',ss=s>0?s:'o suporte',L=x=>x.length?x.map(y=>`<p>• ${y}</p>`).join(''):'<p class="mut">Nenhum destacado.</p>';
 $('#m_o').innerHTML=`<h3>MAPA DA ANÁLISE</h3>${R('Contexto',(V('m_a')||'—')+' · '+(V('m_tf')||'—')+' · '+t)}<p>${V('m_c')}</p><b>Confluências encontradas</b>${L(c)}<b>Pontos de atenção</b>${L(at)}<b>Possíveis cenários</b><p><b>A:</b> se o preço romper ${rs} com confirmação de volume, a ideia de continuação de alta ganha força.</p><p><b>B:</b> se houver rejeição em ${rs} (pavio longo, volume alto), ganha força a ideia de recuo até ${ss}.</p><p><b>C:</b> se o preço perder ${ss}, o cenário de alta perde validade e a estrutura pode mudar.</p>${R('Nível de invalidação',up?String(ss):dn?String(rs):'defina antes de qualquer plano')}<p class="mut"><b>Risco:</b> nenhum cenário é certeza. Defina o stop antes e calcule o tamanho da posição. Isto não é recomendação.</p>`}
/* simulador */
function simCalc(o){const rk=calcRisco({banca:o.b,r:o.r,entrada:o.e,stop:o.sl,lev:o.l});if(!rk)return null;const d=o.side=='short'?-1:1;if((o.sl-o.e)*d>=0)return{err:'O stop deve ficar abaixo da entrada no Long e acima no Short.'};const dtp=isFinite(o.tp)?(o.tp-o.e)*d:NaN,pnl=isFinite(o.x)?rk.qtd*(o.x-o.e)*d:NaN;return{...rk,dtp,rr:dtp/rk.dist,pnl,imp:pnl/o.b*100}}
function simForm(){const P=S.simPre||{},b=S.bank.cur||S.bank.ini||1000;return`<div class="card"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b>${F('s_a','Ativo',P.a||'','text')}${F('s_tf','Timeframe',P.tf||'','text')}<label>Long/Short</label><select id="s_s"><option value="long">Long</option><option value="short" ${P.s=='short'?'selected':''}>Short</option></select>${F('s_e','Entrada',P.e||'')}${F('s_sl','Stop Loss',P.sl||'')}${F('s_tp','Take Profit',P.tp||'')}${F('s_x','Preço de saída (resultado)',P.x||'')}${F('s_b','Banca fictícia',P.b||b)}${F('s_r','Risco %',P.r||S.bank.rop||S.bank.risco||1)}${F('s_l','Alavancagem',P.l||5)}<button class="btn alt" onclick="simRun(0)">Calcular</button><button class="btn" onclick="simRun(1)">${S.simEdit!=null?'Atualizar simulação':'Salvar simulação'}</button><div id="s_o"></div></div>`+simHist()}
function simRun(sv){const o={a:V('s_a').toUpperCase(),tf:V('s_tf'),side:V('s_s'),e:N(V('s_e')),sl:N(V('s_sl')),tp:N(V('s_tp')),x:N(V('s_x')),b:N(V('s_b')),r:N(V('s_r')),l:N(V('s_l'))},c=simCalc(o);
 if(!c||c.err)return $('#s_o').innerHTML=`<p class="neg">${c?c.err:'Preencha banca, risco %, entrada e stop com valores válidos.'}</p>`;
 $('#s_o').innerHTML=R('Valor arriscado',money(c.rd,'USD'))+R('Distância até o stop',c.dist.toFixed(4)+' ('+pct(c.distP)+')')+R('Distância até o alvo',isFinite(c.dtp)?c.dtp.toFixed(4):'—')+R('Risco/retorno',isFinite(c.rr)?'1 : '+c.rr.toFixed(2):'—')+R('Posição / margem',money(c.pos,'USD')+' / '+money(c.margem,'USD'))+R('PnL estimado',isFinite(c.pnl)?money(c.pnl,'USD'):'—',cls(c.pnl))+R('Impacto na banca',isFinite(c.imp)?pct(c.imp):'—',cls(c.imp))+'<p class="mut">SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</p>';
 if(sv){if(!isFinite(c.pnl))return alert('Informe o preço de saída para salvar.');{const rec={...o,rd:c.rd,rr:c.rr,pnl:c.pnl,data:new Date().toISOString().slice(0,10)};if(S.simEdit!=null&&S.simsList[S.simEdit]){rec.data=S.simsList[S.simEdit].data;S.simsList[S.simEdit]=rec}else S.simsList.push(rec)}S.simEdit=null;S.sims=S.simsList.length;S.simPre=null;save();render()}}
function simHist(){const L=S.simsList;if(!L.length)return'<p class="mut">Sem simulações salvas.</p>';const w=L.filter(x=>x.pnl>0),l=L.filter(x=>x.pnl<0),av=a=>a.length?a.reduce((s,x)=>s+x.pnl,0)/a.length:0;let eq=0,pk=0,dd=0,sq=0,ms=0;L.forEach(x=>{eq+=x.pnl;pk=Math.max(pk,eq);dd=Math.max(dd,pk-eq);sq=x.pnl<0?sq+1:0;ms=Math.max(ms,sq)});
 return`<div class="card"><b>Estatísticas das simulações</b>${R('Simulações',L.length)}${R('Ganhos / Perdas',w.length+' / '+l.length)}${R('Taxa de acerto',pct(w.length/L.length*100))}${R('Média de ganho',money(av(w),'USD'))}${R('Média de perda',money(av(l),'USD'))}${R('Maior sequência de perdas',ms)}${R('Drawdown máximo',money(dd,'USD'),'neg')}<p class="mut">Descritivo; não indica desempenho futuro.</p></div><div class="card tbl"><table><tr><th>Data</th><th>Ativo</th><th>L/S</th><th>R:R</th><th>PnL</th><th></th></tr>${L.map((x,ix)=>[x,ix]).reverse().slice(0,30).map(([x,ix])=>`<tr><td>${x.data}</td><td>${x.a}</td><td>${x.side}</td><td>${isFinite(x.rr)?x.rr.toFixed(2):'—'}</td><td class="${cls(x.pnl)}">${money(x.pnl,'USD')}</td><td><button onclick="simEdit(${ix})">✏️</button> <button onclick="simDel(${ix})">🗑</button></td></tr>`).join('')}</table></div><button class="btn alt" onclick="if(confirm('Apagar simulações?')){S.simsList=[];S.sims=0;save();render()}">Limpar simulações</button>`}
/* calculadoras extras */
function maisHTML(o){const h0=o('mais'),tabs=h0.slice(0,h0.indexOf('</div>')+6),I=(i,l,v)=>F(i,l,v).replace('<input','<input oninput="calcM()"');return tabs+`<div class="card"><b>Preço médio</b>${I('pm_e1','Entrada 1',100)}${I('pm_q1','Quantidade 1',1)}${I('pm_e2','Entrada 2',90)}${I('pm_q2','Quantidade 2',1)}<div id="pm_o"></div></div><div class="card"><b>Impacto da perda na banca</b>${I('im_p','Perda na banca (%)',10)}<div id="im_o"></div></div><div class="card"><b>Take profit por risco/retorno</b>${I('tp_e','Entrada',100)}${I('tp_s','Stop',98)}${I('tp_r','Risco/retorno desejado',2)}<div id="tp_o"></div></div><div class="card warn"><b>ESTIMATIVA EDUCACIONAL.</b><p>O preço real de liquidação depende da corretora, contrato, margem, modo de margem, taxas, funding e regras específicas da plataforma.</p>${I('lq_e','Entrada',100)}${I('lq_l','Alavancagem',10)}<label>Lado</label><select id="lq_s" onchange="calcM()"><option value="long">Long</option><option value="short">Short</option></select><div id="lq_o"></div></div>`}
function calcM(){const q=(id,h)=>$('#'+id).innerHTML=h,bad='<p class="mut">Valores inválidos.</p>',e1=N(V('pm_e1')),q1=N(V('pm_q1')),e2=N(V('pm_e2')),q2=N(V('pm_q2'));
 q('pm_o',q1+q2>0&&e1>0&&e2>0?R('Preço médio',((e1*q1+e2*q2)/(q1+q2)).toFixed(4))+R('Quantidade total',q1+q2):bad);const p=N(V('im_p'));q('im_o',p>0&&p<100?R('Ganho necessário para recuperar',pct(p/(100-p)*100)):bad);
 const e=N(V('tp_e')),s=N(V('tp_s')),r=N(V('tp_r'));q('tp_o',e>0&&s>0&&e!==s&&r>0?R('Take profit',(e+(e-s)*r).toFixed(4))+R('Distância até o stop',Math.abs(e-s).toFixed(4)):bad);
 const c=calcFut({margem:1,lev:N(V('lq_l')),entrada:N(V('lq_e')),saida:NaN,side:V('lq_s')});q('lq_o',c?R('Estimativa genérica (NÃO é o preço real)',c.liqPx.toFixed(4)):bad)}
views.calc=(o=>a=>a=='mais'?maisHTML(o):o(a))(views.calc);
/* diário: revisão pós-operação */
const REV=[['Segui meu plano?','y'],['Respeitei o stop?','y'],['Respeitei o risco?','y'],['Entrei por estratégia ou emoção?','Estratégia|Emoção'],['O cenário realmente existia?','y'],['O que eu faria diferente?','t']];
function revHTML(i){const t=S.trades[i];if(!t)return views.diario();const v=t.rev||[];return`<h2>REVISÃO DA OPERAÇÃO</h2><div class="card"><p class="mut">${t.ativo||''} ${t.side||''} ${t.data||''}</p>${REV.map(([l,ty],k)=>`<label>${k+1}. ${l}</label>${ty=='t'?`<textarea id="rv${k}">${v[k]||''}</textarea>`:`<select id="rv${k}"><option></option>${(ty=='y'?['Sim','Não']:ty.split('|')).map(o=>`<option ${v[k]==o?'selected':''}>${o}</option>`).join('')}</select>`}`).join('')}<button class="btn" onclick="revSave(${i})">Salvar revisão</button><a class="btn alt" href="#diario/hist">Pular</a></div>`}
function revSave(i){const t=S.trades[i];if(!t.rev)S.revs++;t.rev=REV.map((_,k)=>V('rv'+k));save();go('diario/hist')}
views.diario=(o=>(a,b)=>a=='rev'?revHTML(+b):o(a))(views.diario);
/* gestão de banca */
function bancaHTML(){const b=S.bank,s=stats(),ini=b.ini||0,atual=ini?ini+s.net:(b.cur||0),hoje=new Date().toISOString().slice(0,10),T=S.trades.filter(x=>x.data==hoje),loss=a=>-a.reduce((z,x)=>z+Math.min(0,x.net||0),0),perdaH=loss(T),riscoH=T.reduce((z,x)=>z+(x.risco||0),0),perdaS=loss(S.trades.filter(x=>Date.now()-new Date(x.data)<7*864e5));
 let eq=ini,pk=ini,dd=0;S.trades.forEach(x=>{eq+=x.net||0;pk=Math.max(pk,eq);dd=Math.max(dd,pk-eq)});
 const rmax=ini*(b.rdia||0)/100,ld=b.ldia||b.lim||0,al=[];if(ld>0&&perdaH>=ld)al.push('Você já atingiu seu limite de perda diária.');if(rmax>0&&riscoH>=rmax)al.push('Você já atingiu seu limite de risco diário.');if(b.lsem>0&&perdaS>=b.lsem)al.push('Você já atingiu seu limite de perda semanal.');if(b.maxops>0&&T.length>=b.maxops)al.push('Você já atingiu o máximo de operações do dia.');
 return`<h3>GESTÃO DE BANCA</h3><div class="card">${[['b_i','Banca inicial',b.ini],['b_r','Risco máximo por operação (%)',b.rop||b.risco],['b_rd','Risco máximo diário (%)',b.rdia],['b_li','Limite de perda diária ($)',ld],['b_ls','Limite de perda semanal ($)',b.lsem],['b_mo','Máx. operações por dia',b.maxops]].map(([i,l,v])=>F(i,l,v||'')).join('')}${F('b_ob','Objetivo de estudo',b.obj||'','text')}<button class="btn" onclick="saveBanca()">Salvar</button></div><div class="card">${R('Banca atual',money(atual))}${R('Lucro/prejuízo acumulado',money(s.net),cls(s.net))}${R('Drawdown máximo',money(dd),'neg')}${R('Risco utilizado hoje',money(riscoH)+(rmax?' de '+money(rmax):''))}${R('Limite de perda restante hoje',ld?money(Math.max(0,ld-perdaH)):'—')}${al.map(x=>`<p class="neg"><b>${x}</b> Considere encerrar o treinamento por hoje.</p>`).join('')}<p class="mut">Nunca aumente o risco para recuperar perdas.</p></div>`}
function saveBanca(){const b=S.bank;b.ini=N(V('b_i'))||0;b.rop=b.risco=N(V('b_r'))||1;b.rdia=N(V('b_rd'))||0;b.ldia=b.lim=N(V('b_li'))||0;b.lsem=N(V('b_ls'))||0;b.maxops=N(V('b_mo'))||0;b.obj=V('b_ob');b.cur=b.ini+stats().net;if(b.ini)b.hist.push({d:new Date().toISOString().slice(0,10),v:b.cur});save();render()}
/* ===== v3: treinamento e estratégias ===== */
S.tr=S.tr||{};
const trScore=i=>Object.values(S.tr[i]||{}).filter(Boolean).length;
views.treino=a=>{if(a===undefined)return`<a href="#aprender">← Aprender</a><h2>Modo Treinamento</h2><p class="mut">Dados fictícios e educacionais. Não são sinais de mercado real.</p>`+TREINOS.map((x,i)=>lnk('treino/'+i,`<b>${x.t}</b><br><span class="mut">${x.ativo} · ${x.tf} · acertos: ${trScore(i)}/${x.q.length}</span>`)).join('');
 const i=+a,x=TREINOS[i];if(!x)return views.treino();
 return`<a href="#treino">← Cenários</a><h2>${x.t}</h2><div class="card warn"><b>TREINAMENTO — DADOS FICTÍCIOS</b>${R('Ativo / timeframe',x.ativo+' · '+x.tf)}${x.d.map(r=>R(r[0],r[1])).join('')}</div>`+x.q.map((q,n)=>`<div class="card"><b>${n+1}. ${q[0]}</b>${q[1].map((o,k)=>`<button class="btn alt opt" onclick="tAns(${i},${n},${k})">${o}</button>`).join('')}<div id="tq${n}"></div></div>`).join('')+`<div class="card"><b id="tsc">Acertos: ${trScore(i)}/${x.q.length}</b><p class="mut">Pontuação apenas educacional. Não indica desempenho financeiro.</p></div>`};
function tAns(i,n,k){const q=TREINOS[i].q[n],ok=k==q[2];S.tr[i]=S.tr[i]||{};S.tr[i][n]=S.tr[i][n]||ok;save();$('#tq'+n).innerHTML=`<p class="${ok?'pos':'neg'}"><b>${ok?'Correto!':'Incorreto. Resposta: '+q[1][q[2]]}</b></p><p>${q[3]}</p>`;$('#tsc').textContent=`Acertos: ${trScore(i)}/${TREINOS[i].q.length}`}
views.estrat=()=>`<a href="#aprender">← Aprender</a><h2>Estratégias (conceitos)</h2><p class="mut">Ideias hipotéticas para estudo. Nenhuma garante resultado.</p>`+ESTRAT.map(e=>`<details class="card"><summary><b>${e[0]}</b></summary>${['Contexto','Entrada hipotética','Stop','Alvo','Risco','O que invalida a ideia','Quando NÃO operar'].map((l,k)=>`<p><b>${l}:</b> ${e[k+1]}</p>`).join('')}</details>`).join('')+AVISO;
/* ===== v4: indicadores e biblioteca ===== */
views.indic=a=>{if(a===undefined)return`<a href="#aprender">← Aprender</a><h2>Indicadores</h2>`+INDIC.map((x,i)=>lnk('indic/'+i,`<b>${x[0]}</b><br><span class="mut">${x[1]}</span>`)).join('');
 const x=INDIC[+a];if(!x)return views.indic();return`<a href="#indic">← Indicadores</a><h2>${x[0]}</h2>${figCard(INDFIG[+a])}${['O que é','Para que serve','Como interpretar','Erros comuns','Como combinar com outros elementos','Exemplo'].map((l,k)=>`<div class="card"><b>${l}</b><p>${x[k+1]}</p></div>`).join('')}<p class="mut">Indicador isolado não é garantia de entrada.</p>`+AVISO};
const BCAT=['Fundamentos','Gráficos','Indicadores','Gestão de risco','Psicologia','Estratégias','Cálculos','Glossário'];let bibCat=-1,bibQ='';
function bibItems(){const map={0:0,1:3,2:1,3:1,4:2,5:2,6:2,7:1,8:5,9:4},I=[];MODULOS.forEach((m,i)=>m.a.forEach((x,j)=>I.push([map[i],x[0],x[1],`aprender/${i}/${j}`])));
 INDIC.forEach((x,i)=>I.push([2,x[0]+' (indicador)',x[1]+' '+x[2],'indic/'+i]));ESTRAT.forEach(e=>I.push([5,'Estratégia: '+e[0],e[1],'estrat']));
 [['Calculadora de futuros','PnL, taxas, funding e liquidação estimada.','calc'],['Calculadora de alavancagem','Efeito de ±1%, 5% e 10% sobre a margem.','calc/alav'],['Risco e tamanho da posição','Quantidade a partir do risco e do stop.','calc/risco'],['USD ⇄ BRL','Conversor com cotação manual.','calc/cambio'],['Preço médio, take profit, impacto da perda, liquidação','Calculadoras complementares.','calc/mais']].forEach(x=>I.push([6,x[0],x[1],x[2]]));
 GLOS.forEach(g=>I.push([7,g[0],g[1],null]));return I}
views.biblio=()=>`<a href="#aprender">← Aprender</a><h2>📚 Biblioteca</h2><input id="bq" placeholder="Buscar…" value="${bibQ}" oninput="bibQ=this.value;bib()"><div class="tabs" style="margin-top:8px"><button class="btn ${bibCat<0?'':'alt'}" onclick="bibC(-1)">Todos</button>${BCAT.map((c,i)=>`<button class="btn ${bibCat==i?'':'alt'}" onclick="bibC(${i})">${c}</button>`).join('')}</div><div id="bl"></div>`;
function bibC(i){bibCat=i;render()}
function bib(){const q=bibQ.toLowerCase(),r=bibItems().filter(x=>(bibCat<0||x[0]==bibCat)&&(x[1]+' '+x[2]).toLowerCase().includes(q));$('#bl').innerHTML=r.slice(0,60).map(x=>{const b=`<b>${x[1]}</b><br><span class="mut">${x[2].slice(0,110)}${x[2].length>110?'…':''}</span>`;return x[3]?lnk(x[3],b):`<div class="card">${b}</div>`}).join('')||'<p class="mut">Nada encontrado.</p>'}
/* ===== v5: figuras didáticas (SVG offline) e aulas longas ===== */
const cs=(cl,st,w=.8)=>cl.map((c,i)=>{const o=i?cl[i-1]:st;return[o,Math.max(o,c)+w*(1+(i%3)*.4),Math.min(o,c)-w*(1+((i+1)%3)*.4),c]});
const sma=(a,n)=>a.map((_,i)=>i<n-1?null:a.slice(i-n+1,i+1).reduce((s,v)=>s+v,0)/n);
const ema=(a,n)=>{const k=2/(n+1);let e=a[0];return a.map(v=>e=v*k+e*(1-k))};
const rsiF=(a,n=14)=>{let g=0,l=0;return a.map((v,i)=>{if(!i)return null;const d=v-a[i-1];if(i<=n){g+=Math.max(d,0);l+=Math.max(-d,0);if(i<n)return null;g/=n;l/=n}else{g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n}return l==0?100:100-100/(1+g/l)})};
const SV=(h,b)=>`<svg viewBox="0 0 320 ${h}" style="width:100%;height:auto;background:var(--bg);border-radius:10px" role="img" aria-label="Ilustração didática">${b}</svg>`;
function chart(c,o={}){const W=320,P=8,vs=o.vol?34:0,H=o.h||170,ph=H-vs-P*2,ex=(o.lines||[]).map(l=>l[0]).concat(...(o.ma||[]).map(m=>m[0].filter(v=>v!=null)),...(o.dots||[]).map(d=>d[0])),all=c.flatMap(x=>[x[1],x[2]]).concat(ex),mx=Math.max(...all),mn=Math.min(...all),y=v=>P+(mx-v)/(mx-mn||1)*ph,bw=(W-2*P)/c.length,x=i=>P+bw*i+bw/2;let s='';
 (o.lines||[]).forEach(l=>s+=`<line x1="${P}" x2="${W-P}" y1="${y(l[0])}" y2="${y(l[0])}" stroke="${l[2]||'#f59e0b'}" stroke-dasharray="4 3"/><text x="${W-P-2}" y="${y(l[0])-3}" font-size="9" text-anchor="end" fill="${l[2]||'#f59e0b'}">${l[1]}</text>`);
 (o.ma||[]).forEach(m=>s+=`<polyline fill="none" stroke="${m[1]}" stroke-width="1.6" points="${m[0].map((v,i)=>v==null?'':x(i)+','+y(v)).filter(Boolean).join(' ')}"/>`);
 c.forEach((k,i)=>{const col=k[3]>=k[0]?'#22c55e':'#ef4444';s+=`<line x1="${x(i)}" x2="${x(i)}" y1="${y(k[1])}" y2="${y(k[2])}" stroke="${col}"/><rect x="${x(i)-bw*.3}" y="${y(Math.max(k[0],k[3]))}" width="${bw*.6}" height="${Math.max(1.5,Math.abs(y(k[0])-y(k[3])))}" fill="${col}"/>`});
 if(o.vol){const vm=Math.max(...o.vol);o.vol.forEach((v,i)=>s+=`<rect x="${x(i)-bw*.3}" y="${H-P-v/vm*(vs-6)}" width="${bw*.6}" height="${v/vm*(vs-6)}" fill="${c[i][3]>=c[i][0]?'#22c55e':'#ef4444'}" opacity=".5"/>`)}
 (o.notes||[]).forEach(n=>s+=`<text x="${x(n[0])}" y="${y(n[1])+(n[3]??-5)}" font-size="9.5" font-weight="700" fill="var(--tx)" text-anchor="middle">${n[2]}</text>`);
 (o.dots||[]).forEach(([a,col])=>a.forEach((v,i)=>{if(v!=null)s+=`<circle cx="${x(i)}" cy="${y(v)}" r="2.4" fill="${col}"/>`}));(o.leg||[]).forEach((l,i)=>s+=`<text x="${P+2}" y="${12+i*11}" font-size="9" fill="${l[1]}">● ${l[0]}</text>`);return SV(H,s)}
function pane(o){const W=320,H=66,P=8,y=v=>P+(o.max-v)/(o.max-o.min)*(H-2*P),n=(o.bars||o.s[0][0]).length,bw=(W-2*P)/n,x=i=>P+bw*i+bw/2;let s='';
 (o.lv||[]).forEach(l=>s+=`<line x1="${P}" x2="${W-P}" y1="${y(l)}" y2="${y(l)}" stroke="var(--mut)" stroke-dasharray="3 3"/><text x="${P+2}" y="${y(l)-2}" font-size="8" fill="var(--mut)">${l}</text>`);
 (o.bars||[]).forEach((v,i)=>s+=`<rect x="${x(i)-bw*.3}" y="${Math.min(y(0),y(v))}" width="${bw*.6}" height="${Math.abs(y(v)-y(0))}" fill="${v>=0?'#22c55e':'#ef4444'}" opacity=".6"/>`);
 (o.s||[]).forEach(([a,col])=>s+=`<polyline fill="none" stroke="${col}" stroke-width="1.5" points="${a.map((v,i)=>v==null?'':x(i)+','+y(v)).filter(Boolean).join(' ')}"/>`);
 return SV(H,s)}
const CL={trend:[102,101,104,103,106,105,108,107,110,109,112],choch:[103,101,105,103,108,105,109,104,101,98,96],sr:[104,107,105,102,100,103,106,108,105,101,100.5,104,107,105,102],ret:[103,106,105,107,106,108,107,109,112,115,113,110,108.5,109,112,114,116],fal:[102,104,103,105,104,106,105,108,109.5,107,105,103,102],vok:[101,100.5,101.5,101,102,101.5,102,104,107,109],pull:[103,106,108,111,109,107,106,108,111,114,116],
 ser:n=>Array.from({length:n},(_,i)=>100+i*.5+3*Math.sin(i/3)),ser2:n=>Array.from({length:n},(_,i)=>100+i*.2+8*Math.sin(i/6)),ser3:n=>Array.from({length:n},(_,i)=>100+(i<18?4-i*.17:(i-17)*.5)*Math.sin(i/2)+(i>24?(i-24)*.7:0))};
const FIG={
anat:[()=>SV(150,`<line x1="90" x2="90" y1="15" y2="135" stroke="#22c55e" stroke-width="2"/><rect x="72" y="45" width="36" height="65" fill="#22c55e"/><line x1="230" x2="230" y1="15" y2="135" stroke="#ef4444" stroke-width="2"/><rect x="212" y="45" width="36" height="65" fill="#ef4444"/><g font-size="9" fill="var(--tx)"><text x="8" y="18">Máxima</text><text x="8" y="140">Mínima</text><text x="8" y="112">Abertura</text><text x="8" y="50">Fechamento</text><text x="118" y="80">Corpo</text><text x="118" y="30">Pavio superior</text><text x="118" y="132">Pavio inferior</text><text x="255" y="50">Abertura</text><text x="255" y="112">Fechamento</text><text x="60" y="8" fill="#22c55e">Candle de alta</text><text x="200" y="8" fill="#ef4444">Candle de baixa</text></g>`),'Anatomia do candle: no de alta o fechamento fica acima da abertura; no de baixa, abaixo.'],
trend:[()=>chart(cs(CL.trend,100),{notes:[[4,106,'HH'],[5,105,'HL',12],[6,108,'HH'],[7,107,'HL',12],[8,110,'HH']],alt:'HH e HL'}),'Alta: topos (HH) e fundos (HL) cada vez mais altos.'],
choch:[()=>chart(cs(CL.choch,100),{lines:[[105,'último HL','#f59e0b']],notes:[[8,104,'perdeu o HL',14]]}),'A perda do último fundo (HL) sinaliza enfraquecimento da estrutura de alta.'],
sr:[()=>chart(cs(CL.sr,100,.6),{lines:[[108.6,'Resistência','#ef4444'],[99.6,'Suporte','#22c55e']]}),'Suporte e resistência: regiões onde o preço já reagiu mais de uma vez.'],
ret:[()=>chart(cs(CL.ret,100),{lines:[[108.6,'Resistência que virou suporte','#f59e0b']],notes:[[12,108.5,'reteste',16]]}),'Rompimento seguido de reteste: a resistência rompida passa a atuar como suporte.'],
fal:[()=>chart(cs(CL.fal,100),{lines:[[107.6,'Resistência','#ef4444']],vol:[5,6,5,6,5,6,5,6,3,3,7,8,9],notes:[[8,109.5,'falso rompimento',-8]]}),'Falso rompimento: passa do nível com volume fraco e volta para a faixa.'],
vok:[()=>chart(cs(CL.vok,100),{lines:[[102.6,'Resistência','#ef4444']],vol:[4,5,4,5,4,5,4,9,10,8],notes:[[8,107,'volume alto',-8]]}),'Rompimento com volume acima do normal indica maior participação.'],
pull:[()=>chart(cs(CL.pull,100),{lines:[[106,'zona de apoio','#22c55e']],notes:[[5,109,'recuo (pullback)',-8],[8,111,'retomada',-8]]}),'Pullback: recuo dentro da tendência de alta até uma zona de apoio.'],
ma:[()=>{const c=CL.ser(44);return chart(cs(c,100,.9),{h:180,ma:[[sma(c,10),'#3b82f6'],[sma(c,25),'#f59e0b']],leg:[['MM10 (curta)','#3b82f6'],['MM25 (longa)','#f59e0b']]})},'Médias móveis: a curta reage rápido; a longa mostra a direção de fundo.'],
rsi:[()=>{const c=CL.ser(40).map((v,i)=>v+3*Math.sin(i/2)),r=rsiF(c);return chart(cs(c,100,.9),{h:130})+pane({s:[[r,'#a855f7']],min:0,max:100,lv:[70,30]})},'Preço (acima) e RSI (abaixo, linhas em 70 e 30). Extremos indicam esticamento, não reversão certa.'],
macd:[()=>{const c=CL.ser2(50),e=ema(c,12).map((v,i)=>v-ema(c,26)[i]),sg=ema(e,9),h=e.map((v,i)=>v-sg[i]),m=Math.max(...e.map(Math.abs))*1.2;return chart(cs(c,100,.9),{h:130})+pane({bars:h,s:[[e,'#3b82f6'],[sg,'#f59e0b']],min:-m,max:m})},'MACD (azul), linha de sinal (laranja) e histograma. Mostram momento, com atraso.'],
boll:[()=>{const c=CL.ser3(40),m=sma(c,20),sd=c.map((_,i)=>i<19?null:Math.sqrt(c.slice(i-19,i+1).reduce((s,v)=>s+(v-m[i])**2,0)/20));return chart(cs(c,100,.7),{h:180,ma:[[m.map((v,i)=>v==null?null:v+2*sd[i]),'#a855f7'],[m,'#f59e0b'],[m.map((v,i)=>v==null?null:v-2*sd[i]),'#a855f7']],leg:[['Bandas (2 desvios)','#a855f7'],['Média 20','#f59e0b']]})},'Bandas de Bollinger: abrem com volatilidade e se fecham quando ela diminui.'],
rr:[()=>SV(140,`<rect x="60" y="15" width="200" height="30" fill="#22c55e" opacity=".35"/><rect x="60" y="45" width="200" height="30" fill="#ef4444" opacity=".35"/><line x1="60" x2="260" y1="45" y2="45" stroke="var(--tx)"/><g font-size="10" fill="var(--tx)"><text x="66" y="34">Alvo (take profit) 106 → retorno 6</text><text x="66" y="62">Entrada 100</text><text x="66" y="92">Stop 98 → risco 2</text><text x="66" y="125" font-weight="700">Risco/retorno = 1 : 3</text></g><rect x="60" y="75" width="200" height="2" fill="#ef4444"/>`),'Plano com limites: o stop define o risco; o alvo define o retorno potencial.']};
const figCard=k=>k?[].concat(k).map(z=>`<div class="card">${FIG[z][0]()}<p class="mut">${FIG[z][1]} Ilustração didática com dados fictícios.</p></div>`).join(''):'';
const EXTRA={'1.1':{f:'rr',t:['Como aplicar: defina primeiro o stop, no ponto em que a ideia deixa de valer; depois calcule o tamanho da posição pelo risco em dinheiro. Nunca escolha o tamanho e depois "ajuste" o stop.','Exemplo: banca de US$ 1.000 e risco de 1% = US$ 10. Entrada 100 e stop 98 (distância 2): quantidade = 10 ÷ 2 = 5 unidades, posição de US$ 500. Alvo em 106 dá relação risco/retorno de 1:3.']},
'2.0':{f:'anat',t:['Como ler: o corpo mostra quem dominou o período entre abertura e fechamento. Corpo grande e pavios curtos indicam controle de um lado; corpo pequeno com pavios longos indica indecisão ou rejeição.','Erro comum: interpretar um candle isolado. Ele só ganha sentido junto com a tendência, o nível próximo e o volume.']},
'2.1':{f:'fal',t:['No falso rompimento o preço ultrapassa um nível, atrai entradas e volta para dentro da faixa. Sinais frequentes: pouco volume, pavio longo e fechamento de volta abaixo do nível.','Como se proteger: espere o fechamento além do nível, observe o volume e defina o stop antes. Se o preço voltar para a faixa, a ideia de rompimento está invalidada.']},
'3.0':{f:'sr',t:['Como marcar: procure regiões onde o preço reagiu mais de uma vez e desenhe uma zona (faixa), não uma linha fina. Mais toques com reação tornam a zona mais relevante, mas nenhuma é garantida.','Uso prático: as zonas ajudam a posicionar stop e alvo. Um stop logo além do suporte e um alvo antes da resistência formam um plano com limites claros.']},
'3.1':{f:'ret',t:['Depois de romper uma resistência, o preço muitas vezes volta para testar o nível (reteste). Se o nível segurar como suporte e o preço reagir, a ideia de continuação ganha força.','Atenção: se o preço voltar e fechar de novo abaixo do nível, o rompimento falhou. Por isso o stop costuma ficar do outro lado do nível rompido.']},
'4.0':{f:'ma',t:['Na figura, a média curta (MM10) acompanha o preço de perto e a longa (MM25) é mais lenta. Quanto menor o número de períodos, mais rápida a reação e mais sinais falsos.','Exemplo: MM10 em gráfico de 15 minutos = média dos últimos 10 candles de 15 minutos. Em gráfico de 1 hora, seriam as últimas 10 horas.']},
'4.1':{f:'ma',t:['Leitura em três passos: (1) o preço está acima ou abaixo da média? (2) a média está inclinada para cima, para baixo ou plana? (3) as médias estão alinhadas ou embaralhadas?','Cuidado: quando as médias ficam planas e se cruzam várias vezes, o mercado costuma estar lateral e os cruzamentos geram sinais falsos.']},
'5.0':{f:'vok',t:['Na figura, o rompimento vem com barras de volume bem maiores que as anteriores: mais participantes empurram o preço. Isso aumenta a chance de continuidade, sem garantir.','Como medir: compare o volume do candle com a média dos últimos candles. "Alto" só faz sentido em relação ao normal daquele ativo e timeframe.']},
'5.1':{f:'fal',t:['Aqui o preço passa da resistência com volume menor que o das velas anteriores e volta. A falta de participação é um ponto de atenção clássico de falso rompimento.','Exercício: em um gráfico real, marque três rompimentos e compare o volume de cada um com a média. Anote no diário quais se sustentaram.']},
'6.0':{f:['rsi','macd'],t:['RSI: mede a força recente, entre 0 e 100. Acima de 70 ou abaixo de 30 indica esticamento, mas em tendência forte ele pode permanecer nesses extremos.','MACD: a linha rápida cruzando a de sinal e o histograma trocando de lado indicam mudança de momento, com atraso. Use como contexto, junto com estrutura e níveis.']},
'6.1':{f:'boll',t:['As bandas se abrem quando a volatilidade aumenta e se fecham quando diminui. Bandas muito apertadas indicam baixa volatilidade e costumam preceder movimentos mais amplos, sem indicar a direção.','Erro comum: tratar o toque na banda como sinal de reversão. Em tendência forte, o preço pode andar colado na banda por vários candles.']},
'7.0':{f:'trend',t:['Cada topo e cada fundo é mais alto que o anterior: HH (higher high) e HL (higher low). Enquanto a sequência se mantém, a estrutura é de alta.','Uso: em tendência de alta, ideias de compra costumam ser estudadas nos HL, com stop abaixo do último HL. Em tendência de baixa vale o inverso, com LH e LL.']},
'7.1':{f:'choch',t:['A estrutura de alta enfraquece quando o preço perde o último fundo (HL). Isso não garante reversão: pode ser apenas correção ou lateralização.','Como reagir: reduza a confiança na ideia de alta, revise o plano e espere novos topos e fundos formarem uma estrutura antes de qualquer decisão.']},
'8.0':{f:'pull',t:['Pullback: em tendência de alta, o preço recua até uma zona de apoio e volta a subir. A entrada hipotética ocorre depois de sinais de retomada, com stop abaixo do fundo do recuo.','Risco: o recuo pode ser o início de uma reversão. Se o preço perder o fundo do recuo, a ideia está invalidada e o stop cumpre seu papel.']}};
const INDFIG={0:'rsi',1:'macd',2:'boll',4:'vok',5:'ma'};
function lessonExtra(i,j){const e=EXTRA[i+'.'+j];return e?figCard(e.f)+e.t.map(p=>`<div class="card">${p}</div>`).join(''):''}
/* ===== v6: aulas longas com cenários (módulos 1, 2 e 10) ===== */
FIG.lev=[()=>SV(150,`<g font-size="9.5" fill="var(--tx)"><text x="8" y="14">Margem: 30</text><rect x="8" y="18" width="12" height="10" fill="#3b82f6"/><text x="8" y="46">3x → posição 90 · perda com −5%: 4,5</text><rect x="8" y="50" width="36" height="10" fill="#22c55e"/><text x="8" y="78">10x → posição 300 · perda: 15 (50% da margem)</text><rect x="8" y="82" width="120" height="10" fill="#f59e0b"/><text x="8" y="110">20x → posição 600 · perda: 30 (100% da margem)</text><rect x="8" y="114" width="240" height="10" fill="#ef4444"/></g>`),'Mesma margem e mesmo movimento de −5%: quanto maior a alavancagem, maior a fatia da margem perdida.'];
EXTRA['0.0']={t:['Spot x futuros: no spot você compra o ativo e passa a possuí-lo; nos futuros você negocia um contrato sobre o preço e pode operar vendido (short). Nos futuros existem margem e liquidação, que não existem no spot sem alavancagem.','Funding: no perpétuo, a cada intervalo definido pela corretora, um lado paga ao outro para manter o preço do contrato perto do preço à vista. Dependendo do lado da posição, o funding pode ser custo ou receita.','🧪 Cenário: você compra 1 unidade no spot a 100 e o preço sobe para 110: ganho de 10 (10%). Em futuros, Long com margem 20 e 10x (posição 200), os mesmos +10% viram +20 antes de custos: 100% sobre a margem. Se o preço cair 10%, a perda também é 20: toda a margem.']};
EXTRA['0.1']={t:['Valor nocional = preço × quantidade. Com margem 50 e alavancagem 4x, a posição é 200. No Long, PnL = quantidade × (saída − entrada); no Short, o sinal se inverte. O PnL não realizado oscila com o preço e só vira resultado quando a posição é fechada.','🧪 Cenário: Short de 2 unidades com entrada em 100. O preço cai para 96: PnL não realizado = 2 × (100 − 96) = +8. Se voltar a 103 antes de você fechar: 2 × (100 − 103) = −6. Nada foi realizado até o fechamento, por isso o lucro "na tela" não é lucro garantido.']};
EXTRA['0.2']={t:['Os custos se somam: taxa de entrada, taxa de saída (sobre o valor da posição), funding e slippage. Em uma posição de 200 com taxa de 0,05% em cada lado, as taxas custam 0,20 no total: pouco por operação, mas relevante quando repetido muitas vezes.','Liquidação: a corretora fecha a posição quando a margem restante fica abaixo do mínimo de manutenção. Com alavancagem alta, a distância até esse ponto é curta, e o preço exato depende das regras da corretora.','🧪 Cenário: Long a 100 com 10x. Uma queda em torno de 10% já pode se aproximar da liquidação. Com 3x, seriam necessários cerca de 33%. A mesma queda que liquida uma posição pode ser suportada por outra com menos alavancagem.']};
EXTRA['1.0']={f:'lev',t:['Alavancagem define quanta exposição você tem por unidade de margem. Ela não muda o preço do ativo: muda o peso de cada variação sobre a sua margem.','Modo de margem: na isolada, a perda fica limitada à margem alocada àquela posição; na cruzada, o saldo da conta serve de garantia e pode expor mais capital. Conheça o modo antes de operar.','🧪 Cenário: margem 30 e queda de 5% do ativo. Com 3x, a posição é 90 e a perda é 4,5 (15% da margem). Com 10x, a posição é 300 e a perda é 15 (50%). Com 20x, a posição é 600 e a perda é 30 (100% da margem, liquidação provável). Mesmo movimento, consequências muito diferentes.']};
EXTRA['1.1'].t.push('Drawdown e recuperação: perder 10% exige ganhar cerca de 11,1% para voltar ao ponto; perder 50% exige ganhar 100%. Por isso proteger a banca vem antes de buscar ganho.','🧪 Cenário: banca de 1.000 e risco de 1% por operação. Após 8 perdas seguidas, a banca fica em cerca de 923 (−7,7%): ainda operável. Com risco de 10% por operação, 8 perdas levam a cerca de 430 (−57%). O tamanho do risco decide se uma sequência ruim é um incômodo ou o fim da banca.');
EXTRA['9.0']={t:['FOMO: o preço já subiu bastante e você entra por medo de perder o movimento. Resultado comum: entrada longe do stop lógico, risco maior e pouco espaço para acertar. Pergunta de controle: "Eu entraria se o preço estivesse 5% mais baixo, com o mesmo cenário?"','Revenge trading: depois de uma perda, você entra rápido para "recuperar". A decisão passa a ser emocional, com posição maior e sem checklist. Sinais de alerta: pular etapas e aumentar o tamanho depois de perder.','🧪 Cenário: perda de US$ 10 em uma operação planejada. Em seguida você abre outra posição com o triplo do tamanho, sem checklist, e perde US$ 30. A perda total (40) é quatro vezes o risco planejado. Regra prática: ao atingir o limite diário, encerre o treinamento por hoje.']};
EXTRA['9.1']={t:['Disciplina é executar o plano escrito, não acertar sempre. Um bom processo pode gerar perdas individuais e um mau processo pode gerar ganhos por sorte; ambos se revelam no diário ao longo de muitas operações.','Rotina sugerida: antes (checklist e plano), durante (respeitar stop e limites, sem mexer por impulso) e depois (registrar no diário e fazer a revisão da operação).','🧪 Cenário: em 10 operações você seguiu o plano em 8 e quebrou o stop em 2. As 2 quebradas concentram a maior parte do prejuízo. A revisão mostra que o problema não foi a estratégia, e sim a execução: o ajuste está no hábito, não no método.']};
/* ===== v7: editar operações e simulações ===== */
const EF=[['data','Data','date'],['hora','Hora','time'],['ativo','Ativo','text'],['tf','Timeframe','text'],['entrada','Entrada','n'],['saida','Saída','n'],['margem','Margem','n'],['lev','Alavancagem','n'],['stop','Stop','n'],['tp','Take Profit','n'],['risco','Risco ($)','n'],['bruto','Resultado bruto','n'],['taxas','Taxas','n'],['fund','Funding','n'],['motivo','Motivo','text'],['nota','Print/anotação','text']];
function editHTML(i){const t=S.trades[i];if(!t)return views.diario('hist');const cv=v=>(v==null||(typeof v=='number'&&!isFinite(v)))?'':String(v).replace(/"/g,'&quot;');
 return`<h2>Editar operação</h2><div class="card"><label>Long/Short</label><select id="e_side"><option value="long" ${t.side=='long'?'selected':''}>Long</option><option value="short" ${t.side=='short'?'selected':''}>Short</option></select>${EF.map(([k,l,ty])=>F('e_'+k,l,cv(t[k]),ty=='n'?'number':ty)).join('')}<p class="mut">Deixe o bruto vazio para recalcular por entrada, saída, margem e alavancagem.</p><button class="btn" onclick="editSave(${i})">Salvar alterações</button><a class="btn alt" href="#diario/hist">Cancelar</a></div>`}
function editSave(i){const t=S.trades[i];EF.forEach(([k,,ty])=>{const v=V('e_'+k);t[k]=ty=='n'?(Number.isFinite(N(v))?N(v):''):v});t.side=V('e_side')||t.side;
 if(!Number.isFinite(t.bruto)){const r=calcFut({margem:t.margem,lev:t.lev,entrada:t.entrada,saida:t.saida,side:t.side});t.bruto=r&&isFinite(r.bruto)?r.bruto:0}
 ['taxas','fund','risco'].forEach(k=>{if(!Number.isFinite(t[k]))t[k]=0});t.net=t.bruto-t.taxas-t.fund;save();go('diario/hist')}
views.diario=(o=>(a,b)=>a=='edit'?editHTML(+b):o(a,b))(views.diario);
function simEdit(ix){const x=S.simsList[ix];if(!x)return;S.simPre={a:x.a,tf:x.tf,s:x.side,e:x.e,sl:x.sl,tp:x.tp,l:x.l,x:x.x,b:x.b,r:x.r};S.simEdit=ix;save();go('analisar/sim');render()}
function simDel(ix){if(confirm('Excluir simulação?')){S.simsList.splice(ix,1);S.sims=S.simsList.length;S.simEdit=null;save();render()}}
/* ===== v8: novas figuras (SAR, ATR, PnL, liquidação, reversão, spot x futuros) ===== */
function sarF(c,a0=.02,am=.2){let up=true,sar=c[0][2],ep=c[0][1],af=a0;const o=[sar];for(let i=1;i<c.length;i++){sar+=af*(ep-sar);if(up){sar=Math.min(sar,c[i-1][2],i>1?c[i-2][2]:c[i-1][2]);if(c[i][2]<sar){up=false;sar=ep;ep=c[i][2];af=a0}else if(c[i][1]>ep){ep=c[i][1];af=Math.min(af+a0,am)}}else{sar=Math.max(sar,c[i-1][1],i>1?c[i-2][1]:c[i-1][1]);if(c[i][1]>sar){up=true;sar=ep;ep=c[i][1];af=a0}else if(c[i][2]<ep){ep=c[i][2];af=Math.min(af+a0,am)}}o.push(sar)}return o}
FIG.sar=[()=>{const c=cs([101,103,104,106,107,109,110,108,106,105,103,102,101,103,105,107,108,110],100,.6),d=sarF(c);return chart(c,{h:170,dots:[[d,'#a855f7']],leg:[['Pontos do SAR','#a855f7']]})},'SAR: os pontos ficam abaixo do preço na alta e acima na baixa; a inversão é um aviso, não uma ordem.'];
FIG.atr=[()=>{const c0=CL.ser(34).map((v,i)=>v+(i>18?4*Math.sin(i):1.2*Math.sin(i))),c=cs(c0,100,.7),tr=c.map((k,i)=>i?Math.max(k[1]-k[2],Math.abs(k[1]-c[i-1][3]),Math.abs(k[2]-c[i-1][3])):k[1]-k[2]),a=sma(tr,10);return chart(c,{h:130})+pane({s:[[a,'#f59e0b']],min:0,max:Math.ceil(Math.max(...a.filter(v=>v!=null)))+1})},'Preço (acima) e ATR (abaixo): a volatilidade sobe quando os candles ficam mais amplos.'];
FIG.pnl=[()=>SV(150,`<line x1="20" x2="300" y1="75" y2="75" stroke="var(--mut)"/><line x1="160" x2="160" y1="10" y2="140" stroke="var(--mut)" stroke-dasharray="3 3"/><line x1="40" y1="125" x2="280" y2="25" stroke="#22c55e" stroke-width="2.5"/><line x1="40" y1="25" x2="280" y2="125" stroke="#ef4444" stroke-width="2.5"/><g font-size="9.5" fill="var(--tx)"><text x="200" y="36" fill="#22c55e">Long: lucra se o preço sobe</text><text x="46" y="138" fill="#22c55e">Long perde se cai</text><text x="46" y="20" fill="#ef4444">Short: lucra se o preço cai</text><text x="196" y="138" fill="#ef4444">Short perde se sobe</text><text x="163" y="70">Entrada</text><text x="252" y="88" fill="var(--mut)">Preço →</text><text x="164" y="18" fill="var(--mut)">PnL ↑</text></g>`),'PnL de Long e Short em relação ao preço de entrada (antes de custos).'];
FIG.spot=[()=>SV(150,`<line x1="20" x2="300" y1="130" y2="130" stroke="var(--mut)"/><rect x="70" y="121" width="60" height="9" fill="#3b82f6"/><rect x="190" y="40" width="60" height="90" fill="#f59e0b"/><g font-size="9.5" fill="var(--tx)" text-anchor="middle"><text x="100" y="114">+10%</text><text x="220" y="33">+100%</text><text x="100" y="144">Spot (100)</text><text x="220" y="144">Futuros 10x (margem 20)</text></g>`),'Mesmo movimento de +10% do ativo: o retorno sobre o capital usado é muito maior nos futuros alavancados, e a perda também seria.'];
FIG.liq=[()=>chart(cs([99,97,98,95,94,96,93,92,91,92],100,.6),{h:190,lines:[[100,'Entrada','#3b82f6'],[90.5,'Liquidação aprox. com 10x','#ef4444'],[67,'Liquidação aprox. com 3x','#f59e0b']]}),'Estimativa educacional: o preço real de liquidação depende da corretora, do contrato e do modo de margem.'];
FIG.rev=[()=>{const c=cs([108,106,104,102,100,98.5,99,101,103,104],110,.6);c[5]=[100,100.4,94.5,99];return chart(c,{lines:[[95,'Suporte','#22c55e']],notes:[[5,94.5,'rejeição (pavio longo)',14]]})},'Reversão: só é estudada com sinais de rejeição em uma zona relevante.'];
EXTRA['0.0'].f='spot';EXTRA['0.1'].f='pnl';EXTRA['0.2'].f='liq';EXTRA['6.1'].f=['boll','sar','atr'];INDFIG[3]='sar';INDFIG[6]='atr';
EXTRA['8.1']={f:'rev',t:['Reversão: só faz sentido estudar quando há sinais de rejeição em uma zona relevante, como o pavio longo na figura. Entrar contra a tendência sem rejeição é apenas tentar adivinhar o fundo.','Confluência: combine fatores independentes. Exemplo: suporte testado várias vezes + pavio de rejeição + volume alto na rejeição + RSI saindo de zona esticada. Quatro fatores diferentes valem mais que quatro indicadores que medem o mesmo momento.','🧪 Cenário: suporte em 95 e rejeição com fechamento em 99. Plano hipotético: entrada 99, stop 94 (abaixo do pavio, risco 5) e alvo 109 (retorno 10), relação 1:2. A ideia é invalidada se o preço fechar abaixo de 94. Sem a rejeição, o plano nem existiria.']};
addEventListener('hashchange',render);render();
