const $=s=>document.querySelector(s),app=$('#app');
const V=id=>{const e=document.getElementById(id);return e?e.value:''};
const F=(id,l,v='',t='number')=>`<label>${l}</label><input id="${id}" type="${t}" inputmode="${t=='number'?'decimal':'text'}" step="any" value="${v}">`;
const R=(l,v,c='')=>`<div class="row"><span>${l}</span><b class="${c}">${v}</b></div>`;
const AVISO='<div class="card warn"><b>ATENÇÃO AO RISCO</b><p class="mut">Conteúdo educacional; nenhuma estratégia garante lucro. Alavancagem aumenta exposição e perdas podem ser rápidas. Stop não elimina todos os riscos. Liquidação pode ocorrer. Taxas, funding e slippage reduzem o resultado. Resultados passados não garantem resultados futuros.</p></div>';
document.documentElement.dataset.theme=S.cfg.theme;
const prog=()=>{const m=Object.keys(S.done).length,q=Object.keys(S.quiz).length,c=Object.values(S.check).filter(x=>x===true).length;return{m,q,c,qp:Math.round(Object.values(S.quiz).filter(x=>x).length/QUIZ.length*100)}};
const bar=p=>`<div class="bar"><i style="width:${p}%"></i></div>`;
const stats=()=>{const t=S.trades,n=t.length,w=t.filter(x=>x.net>0),l=t.filter(x=>x.net<0),sum=k=>t.reduce((a,x)=>a+(x[k]||0),0);
 let sw=0,sl=0,mw=0,ml=0;t.forEach(x=>{if(x.net>0){sw++;sl=0}else if(x.net<0){sl++;sw=0}mw=Math.max(mw,sw);ml=Math.max(ml,sl)});
 const grp=k=>{const o={};t.forEach(x=>o[x[k]||'—']=(o[x[k]||'—']||0)+(x.net||0));return o};
 return{n,w:w.length,l:l.length,rate:n?w.length/n*100:NaN,bruto:sum('bruto'),taxas:sum('taxas'),fund:sum('fund'),net:sum('net'),max:Math.max(0,...t.map(x=>x.net||0)),min:Math.min(0,...t.map(x=>x.net||0)),mg:w.length?w.reduce((a,x)=>a+x.net,0)/w.length:0,mp:l.length?l.reduce((a,x)=>a+x.net,0)/l.length:0,mw,ml,ativo:grp('ativo'),tf:grp('tf'),side:grp('side')}};
const grpHTML=o=>Object.entries(o).map(([k,v])=>R(k,money(v),cls(v))).join('')||'<p class="mut">Sem dados.</p>';

const views={
inicio(){if(!S.welcomed)return`<div class="card"><h2>Bem-vindo ao Futures Trader Academy</h2><p>Aprenda primeiro. Simule depois. Registre suas operações. Só então considere operar com dinheiro real.</p><button class="btn" onclick="S.welcomed=true;save();go('aprender')">Começar aprendizado</button></div>`+AVISO;
 const p=prog(),s=stats(),u=S.trades[S.trades.length-1];
 return`<h2>Central de Trading</h2><div class="card"><b>Seu progresso</b>${bar(p.m/MODULOS.length*100)}<p class="mut">Módulos: ${p.m}/${MODULOS.length} · Checklist: ${p.c}/${CHECK.length} · Quiz: ${p.qp}% · Simulações: ${S.sims} · Operações: ${s.n}</p></div>
 <div class="grid"><div class="card"><span class="mut">Resultado do diário</span><div class="kpi ${cls(s.net)}">${money(s.net)}</div></div><div class="card"><span class="mut">Taxa de acerto</span><div class="kpi">${pct(s.rate)}</div></div></div>
 <div class="card"><span class="mut">Última operação</span><div>${u?`${u.data||''} · ${u.ativo||''} ${u.side||''} · <b class="${cls(u.net)}">${money(u.net)}</b>`:'Nenhuma registrada'}</div></div>
 <a class="btn" href="#aprender">Começar estudo</a><a class="btn alt" href="#analisar">Checklist de operação</a><a class="btn alt" href="#calc">Calculadoras</a><a class="btn alt" href="#diario">Diário de operações</a>`+AVISO},
aprender(a){if(a){const i=+a,m=MODULOS[i];return`<a href="#aprender">← Módulos</a><h2>${m.t}</h2>${m.b.map(x=>`<div class="card">${x}</div>`).join('')}<button class="btn ${S.done[i]?'ok':''}" onclick="S.done[${i}]=!S.done[${i}];if(!S.done[${i}])delete S.done[${i}];save();render()">${S.done[i]?'✓ Concluído':'Marcar como concluído'}</button>`+AVISO}
 return`<h2>Aprender</h2>${MODULOS.map((m,i)=>`<a class="card" style="display:block;text-decoration:none;color:inherit" href="#aprender/${i}"><b>${S.done[i]?'✅':'▫️'} ${m.t}</b></a>`).join('')}<a class="btn alt" href="#quiz">Fazer quiz (${prog().qp}%)</a>`},
quiz(a){const i=+a||0;if(i>=QUIZ.length)return`<div class="card"><h2>Quiz concluído</h2><p>Acertos: ${prog().qp}%</p><button class="btn" onclick="S.quiz={};save();go('quiz/0')">Refazer</button></div>`;
 const q=QUIZ[i];return`<h2>Quiz ${i+1}/${QUIZ.length}</h2>${bar(i/QUIZ.length*100)}<div class="card"><b>${q[0]}</b>${q[1].map((o,k)=>`<button class="btn alt opt" onclick="ans(${i},${k})">${o}</button>`).join('')}<div id="fb"></div></div>`},
analisar(a){const t=`<div class="tabs"><a class="btn ${!a?'':'alt'}" href="#analisar">Checklist</a><a class="btn ${a=='tec'?'':'alt'}" href="#analisar/tec">Análise técnica</a><a class="btn ${a=='sim'?'':'alt'}" href="#analisar/sim">Simulador</a></div>`;
 if(a=='tec')return t+`<div class="card"><h3>Análise técnica</h3><p>Monte sua própria leitura: contexto (tendência), estrutura (suporte, resistência, topos, fundos), confirmação (médias, volume, RSI, MACD) e cenário. Indicadores nem sempre concordam e não precisam estar todos ativos.</p><p class="mut">Cenários possíveis: alta, baixa ou espera. Nunca são certeza.</p><a class="btn" href="#aprender">Revisar módulos</a></div>`;
 if(a=='sim')return t+`<div class="card"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b>${F('s_b','Banca fictícia',1000)}<label>Long/Short</label><select id="s_s"><option value="long">Long</option><option value="short">Short</option></select>${F('s_e','Entrada',100)}${F('s_x','Saída',105)}${F('s_l','Alavancagem',10)}${F('s_st','Stop Loss (opcional)')}${F('s_tp','Take Profit (opcional)')}${F('s_m','Margem usada',100)}<button class="btn" onclick="sim()">Simular</button><div id="s_o"></div></div>`;
 const c=S.check,val=k=>c[k]||'';
 return t+`<div class="card"><h3>Checklist pré-operação</h3>${F('c_ativo','1. Ativo',val('ativo'),'text')}${F('c_tf','Timeframe principal',val('tf'),'text')}<label>Tendência</label><select id="c_tr">${['Alta','Baixa','Lateral'].map(x=>`<option ${val('tr')==x?'selected':''}>${x}</option>`).join('')}</select>
 <p class="mut">2–3. Estrutura e indicadores</p>${CHECK.map((x,i)=>`<label style="color:var(--tx)"><input type="checkbox" style="width:auto;min-height:0" ${c['k'+i]?'checked':''} onchange="S.check.k${i}=this.checked;save()"> ${x}</label>`).join('')}
 <label>4. Hipótese</label><select id="c_h">${['LONG','SHORT','NÃO OPERAR'].map(x=>`<option ${val('h')==x?'selected':''}>${x}</option>`).join('')}</select><label>Justificativa</label><textarea id="c_j">${val('j')}</textarea>
 ${F('c_e','5. Preço de entrada',val('e'))}${F('c_s','6. Preço do stop',val('s'))}${F('c_p','Valor máximo que aceita perder',val('p'))}${F('c_t','7. Preço alvo',val('t'))}<button class="btn alt" onclick="chk()">Calcular e concluir</button><div id="c_o"></div></div>`},
calc(a){const t=`<div class="tabs">${[['','Futuros'],['alav','Alavancagem'],['risco','Risco'],['cambio','USD⇄BRL']].map(([k,n])=>`<a class="btn ${a==k||(!a&&!k)?'':'alt'}" href="#calc${k?'/'+k:''}">${n}</a>`).join('')}</div>`;
 const ipt=(ids)=>`oninput="${ids}()"`;
 if(a=='alav')return t+`<div class="card"><b>Calculadora de alavancagem</b>${F('a_m','Margem',20).replace('<input','<input oninput="calcA()"')}${F('a_l','Alavancagem (x)',10).replace('<input','<input oninput="calcA()"')}<div id="a_o"></div><p class="mut">Aproximação antes de taxas, funding e slippage. 10x não significa ganhar 10 vezes o dinheiro.</p></div>`;
 if(a=='risco')return t+`<div class="card"><b>Risco e tamanho da posição</b>${['r_b|Banca|'+(S.bank.cur||1000),'r_r|Risco máximo (%)|'+(S.bank.risco||1),'r_e|Entrada|100','r_s|Stop Loss|98','r_l|Alavancagem|5'].map(x=>{const[i,l,v]=x.split('|');return F(i,l,v).replace('<input','<input oninput="calcR()"')}).join('')}<div id="r_o"></div></div>`;
 if(a=='cambio')return t+`<div class="card"><b>Conversor</b>${F('f_v','Valor',20).replace('<input','<input oninput="calcF()"')}${F('f_c','Cotação usada (R$ por US$)',S.cfg.fx).replace('<input','<input oninput="calcF()"')}<label>Direção</label><select id="f_d" onchange="calcF()"><option value="u">USD → BRL</option><option value="b">BRL → USD</option></select><div id="f_o"></div></div>`;
 return t+`<div class="card"><b>Calculadora de Futuros (modelo genérico)</b>${F('k_a','Ativo','BTCUSDT','text')}<label>Long/Short</label><select id="k_s" onchange="calcK()"><option value="long">Long</option><option value="short">Short</option></select>${[['k_m','Margem',20],['k_l','Alavancagem',10],['k_e','Preço de entrada',100],['k_x','Preço de saída',105],['k_sl','Stop Loss',''],['k_tp','Take Profit',''],['k_fe','Taxa de entrada (%)',0.05],['k_fs','Taxa de saída (%)',0.05],['k_fu','Funding (%)',0]].map(([i,l,v])=>F(i,l,v).replace('<input','<input oninput="calcK()"')).join('')}<div id="k_o"></div><p class="mut">Liquidação é uma APROXIMAÇÃO genérica; corretoras usam fórmulas próprias. Taxas e funding reais variam.</p></div>`},
diario(a){const s=stats();const fld=[['d_data','Data',new Date().toISOString().slice(0,10),'date'],['d_hora','Hora',new Date().toTimeString().slice(0,5),'time'],['d_ativo','Ativo','','text'],['d_tf','Timeframe','','text'],['d_e','Preço de entrada'],['d_x','Preço de saída'],['d_m','Margem'],['d_l','Alavancagem'],['d_st','Stop'],['d_tp','Take Profit'],['d_taxas','Taxas'],['d_fund','Funding']];
 return`<h2>Meu Diário</h2><div class="tabs"><a class="btn ${a?'alt':''}" href="#diario">Novo</a><a class="btn ${a=='hist'?'':'alt'}" href="#diario/hist">Histórico</a><a class="btn ${a=='est'?'':'alt'}" href="#diario/est">Estatísticas</a><a class="btn ${a=='banca'?'':'alt'}" href="#diario/banca">Banca</a></div>`+
 (a=='hist'?`<div class="card tbl"><table><tr><th>Data</th><th>Ativo</th><th>L/S</th><th>Líquido</th><th></th></tr>${S.trades.slice().reverse().map((x,i)=>`<tr><td>${x.data||''}</td><td>${x.ativo||''}</td><td>${x.side||''}</td><td class="${cls(x.net)}">${money(x.net)}</td><td><button onclick="delT(${S.trades.length-1-i})">🗑</button></td></tr>`).join('')}</table></div><button class="btn alt" onclick="exportCSV()">Exportar CSV</button>`
 :a=='est'?`<div class="card">${R('Total de operações',s.n)}${R('Positivas / Negativas',s.w+' / '+s.l)}${R('Taxa de acerto',pct(s.rate))}${R('Resultado bruto',money(s.bruto),cls(s.bruto))}${R('Taxas',money(s.taxas))}${R('Funding',money(s.fund))}${R('Resultado líquido',money(s.net),cls(s.net))}${R('Maior ganho',money(s.max))}${R('Maior perda',money(s.min))}${R('Média de ganho',money(s.mg))}${R('Média de perda',money(s.mp))}${R('Sequência de ganhos / perdas',s.mw+' / '+s.ml)}</div><div class="card"><b>Por ativo</b>${grpHTML(s.ativo)}<b>Por timeframe</b>${grpHTML(s.tf)}<b>Long / Short</b>${grpHTML(s.side)}</div><div class="card"><b>Resultado por operação</b><div class="hb">${S.trades.map(x=>`<i title="${money(x.net)}" style="height:${Math.max(4,Math.abs(x.net||0)/(Math.max(s.max,-s.min)||1)*100)}%;background:${x.net>=0?'var(--ok)':'var(--bad)'}"></i>`).join('')}</div></div><p class="mut">Estatísticas descritivas; não indicam desempenho futuro.</p>`
 :a=='banca'?bancaHTML()
 :`<div class="card"><label>Long/Short</label><select id="d_side"><option value="long">Long</option><option value="short">Short</option></select>${fld.map(([i,l,v,t])=>F(i,l,v||'',t||'number')).join('')}<p class="mut">Se deixar em branco, o resultado bruto é estimado por entrada/saída/margem/alavancagem.</p>${F('d_bruto','Resultado bruto (opcional)')}${[['d_why','Motivo da entrada'],['d_est','Estratégia utilizada'],['d_eb','Emoção antes da entrada'],['d_ea','Emoção depois da saída'],['d_ok','O que fiz certo?'],['d_no','O que fiz errado?'],['d_ap','O que aprendi?']].map(([i,l])=>`<label>${l}</label><textarea id="${i}"></textarea>`).join('')}<button class="btn" onclick="addT()">Salvar operação</button></div>`)},
config(){return`<h2>Configurações</h2><div class="card"><label>Tema</label><select onchange="S.cfg.theme=this.value;save();document.documentElement.dataset.theme=this.value"><option value="dark" ${S.cfg.theme=='dark'?'selected':''}>Escuro</option><option value="light" ${S.cfg.theme=='light'?'selected':''}>Claro</option></select><label>Moeda padrão</label><select onchange="S.cfg.moeda=this.value;save()"><option ${S.cfg.moeda=='USD'?'selected':''}>USD</option><option ${S.cfg.moeda=='BRL'?'selected':''}>BRL</option></select>${F('cfg_fx','Cotação USD/BRL',S.cfg.fx).replace('<input','<input onchange="S.cfg.fx=N(this.value)||5.5;save()"')}</div><button class="btn" onclick="exportJSON()">Exportar dados (JSON)</button><button class="btn alt" onclick="exportCSV()">Exportar diário (CSV)</button><label class="btn alt">Importar dados (JSON)<input type="file" accept=".json" hidden onchange="importJSON(this.files[0])"></label><button class="btn alt" style="color:var(--bad)" onclick="if(confirm('Apagar todos os dados?')){localStorage.removeItem(KEY);location.reload()}">Limpar dados</button>`+AVISO}};
function bancaHTML(){const b=S.bank,net=stats().net,cur=(b.cur||b.ini||0),v=b.ini?(cur-b.ini)/b.ini*100:NaN;
 return`<div class="card">${[['b_i','Banca inicial',b.ini],['b_c','Banca atual',b.cur],['b_me','Meta diária (opcional)',b.meta],['b_li','Limite diário de perda',b.lim],['b_r','Risco por operação (%)',b.risco]].map(([i,l,v])=>F(i,l,v||'')).join('')}<button class="btn" onclick="saveBanca()">Salvar banca</button>${R('Lucro/prejuízo',money(cur-b.ini),cls(cur-b.ini))}${R('Variação',pct(v))}${R('Resultado do diário',money(net),cls(net))}<b>Evolução</b><div class="hb">${b.hist.map(h=>`<i title="${h.v}" style="height:${Math.max(4,h.v/(Math.max(...b.hist.map(x=>x.v))||1)*100)}%"></i>`).join('')}</div></div>`}
function saveBanca(){const b=S.bank;b.ini=N(V('b_i'))||0;b.cur=N(V('b_c'))||0;b.meta=N(V('b_me'))||0;b.lim=N(V('b_li'))||0;b.risco=N(V('b_r'))||1;if(b.cur)b.hist.push({d:new Date().toISOString().slice(0,10),v:b.cur});save();render()}
function addT(){const g=N(V('d_e')),m=N(V('d_m')),l=N(V('d_l')),x=N(V('d_x')),side=V('d_side');let bruto=N(V('d_bruto'));
 if(!isFinite(bruto)){const r=calcFut({margem:m,lev:l,entrada:g,saida:x,side});bruto=r?r.bruto:0}
 const taxas=N(V('d_taxas'))||0,fund=N(V('d_fund'))||0;
 S.trades.push({data:V('d_data'),hora:V('d_hora'),ativo:V('d_ativo').toUpperCase(),side,tf:V('d_tf'),entrada:g,saida:x,margem:m,lev:l,stop:N(V('d_st')),tp:N(V('d_tp')),bruto,taxas,fund,net:bruto-taxas-fund,motivo:V('d_why'),estrategia:V('d_est'),emoAntes:V('d_eb'),emoDepois:V('d_ea'),certo:V('d_ok'),errado:V('d_no'),aprendi:V('d_ap')});save();alert('Operação salva.');go('diario/hist')}
function delT(i){if(confirm('Excluir operação?')){S.trades.splice(i,1);save();render()}}
function ans(i,k){const q=QUIZ[i],ok=k==q[2];S.quiz[i]=ok;save();$('#fb').innerHTML=`<p class="${ok?'pos':'neg'}"><b>${ok?'Correto!':'Incorreto. Resposta: '+q[1][q[2]]}</b></p><p>${q[3]}</p><a class="btn" href="#quiz/${i+1}">Próxima</a>`}
function chk(){const c=S.check;c.ativo=V('c_ativo');c.tf=V('c_tf');c.tr=V('c_tr');c.h=V('c_h');c.j=V('c_j');c.e=V('c_e');c.s=V('c_s');c.p=V('c_p');c.t=V('c_t');save();
 const rr=calcRR(N(c.e),N(c.s),N(c.t));$('#c_o').innerHTML=(rr?R('Risco (por unidade)',rr.risco.toFixed(4))+R('Retorno potencial',rr.ret.toFixed(4))+R('Risco/retorno','1 : '+rr.rr.toFixed(2)):'<p class="mut">Preencha entrada, stop e alvo para calcular.</p>')+`<div class="card"><b>Checklist concluído.</b><p>Você definiu um cenário. Agora revise os riscos antes de executar.</p><button class="btn" onclick="regChk()">Registrar operação</button></div>`}
function regChk(){const c=S.check;S.trades.push({data:new Date().toISOString().slice(0,10),ativo:(c.ativo||'').toUpperCase(),side:c.h=='SHORT'?'short':'long',tf:c.tf,entrada:N(c.e),stop:N(c.s),tp:N(c.t),bruto:0,taxas:0,fund:0,net:0,motivo:c.j});save();go('diario/hist')}
function sim(){const r=calcFut({margem:N(V('s_m')),lev:N(V('s_l')),entrada:N(V('s_e')),saida:N(V('s_x')),side:V('s_s'),fe:0.05,fs:0.05});if(!r)return $('#s_o').innerHTML='<p class="neg">Valores inválidos.</p>';S.sims++;save();
 $('#s_o').innerHTML=R('Posição',money(r.pos,'USD'))+R('Variação',pct(r.var_))+R('Resultado líquido (taxas 0,05%+0,05%)',money(r.liq,'USD'),cls(r.liq))+R('Banca fictícia final',money(N(V('s_b'))+r.liq,'USD'))+R('Liquidação aprox.',money(r.liqPx,'USD'))+'<p class="mut"><b>SIMULAÇÃO — NÃO É UMA OPERAÇÃO REAL</b></p>'}
function calcK(){const r=calcFut({margem:N(V('k_m')),lev:N(V('k_l')),entrada:N(V('k_e')),saida:N(V('k_x')),side:V('k_s'),fe:N(V('k_fe'))||0,fs:N(V('k_fs'))||0,fund:N(V('k_fu'))||0});
 $('#k_o').innerHTML=r?R('Valor da posição',money(r.pos,'USD'))+R('Quantidade',(r.pos/N(V('k_e'))).toFixed(6))+R('Variação do ativo (lado)',pct(r.var_))+R('PnL bruto',money(r.bruto,'USD'),cls(r.bruto))+R('Taxas estimadas',money(r.taxas,'USD'))+R('Funding estimado',money(r.fundv,'USD'))+R('PnL líquido estimado',money(r.liq,'USD'),cls(r.liq))+R('Retorno sobre a margem',pct(r.roi),cls(r.roi))+R('Liquidação (aprox., genérico)',money(r.liqPx,'USD')):'<p class="mut">Informe margem, alavancagem ≥ 1 e entrada > 0.</p>'}
function calcA(){const m=N(V('a_m')),l=N(V('a_l'));if(!(m>0&&l>=1))return $('#a_o').innerHTML='<p class="mut">Valores inválidos.</p>';
 $('#a_o').innerHTML=R('MARGEM',money(m,'USD'))+R('VALOR DA POSIÇÃO',money(m*l,'USD'))+[1,5,10,-1,-5,-10].map(p=>R('Ativo '+(p>0?'+':'')+p+'%','PnL bruto ≈ '+money(m*l*p/100,'USD'),cls(p))).join('')}
function calcR(){const r=calcRisco({banca:N(V('r_b')),r:N(V('r_r')),entrada:N(V('r_e')),stop:N(V('r_s')),lev:N(V('r_l'))});
 $('#r_o').innerHTML=r?R('Risco máximo em dinheiro',money(r.rd,'USD'))+R('Distância até o stop',r.dist.toFixed(4)+' ('+pct(r.distP)+')')+R('Tamanho estimado da posição',money(r.pos,'USD'))+R('Quantidade',r.qtd.toFixed(6))+R('Margem necessária',money(r.margem,'USD'))+`<p class="mut">Cálculo: risco ($) ÷ distância até o stop = quantidade; quantidade × entrada = posição. A margem não é o risco: o risco é o que você perde se o stop for atingido.${r.pctBanca>100*N(V('r_l'))?'':''}</p>`:'<p class="mut">Informe valores válidos (entrada ≠ stop).</p>'}
function calcF(){const v=N(V('f_v')),c=N(V('f_c'));$('#f_o').innerHTML=v>=0&&c>0?R('Resultado',V('f_d')=='u'?money(v*c,'BRL'):money(v/c,'USD')):'<p class="mut">Valores inválidos.</p>'}
function go(h){location.hash=h}
function render(){const[h,a]=(location.hash.slice(1)||'inicio').split('/'),v=views[h]||views.inicio;app.innerHTML=v(a);document.querySelectorAll('nav a').forEach(x=>x.classList.toggle('on',x.getAttribute('href')=='#'+({quiz:'aprender'}[h]||h)));scrollTo(0,0);
 ({calc:()=>({undefined:calcK,alav:calcA,risco:calcR,cambio:calcF}[a]||calcK)()})[h]?.()}
addEventListener('hashchange',render);render();
