const MODULOS=[
{t:'1. Introdução ao mercado futuro',a:[['Futuros e perpétuos','Futuro é um contrato sobre o preço de um ativo. O perpétuo não tem vencimento e usa funding para ficar próximo do preço à vista (spot). Spot é a compra do ativo em si.'],['Posição, margem e PnL','Long lucra com alta, Short com queda. Valor nocional = margem × alavancagem. PnL não realizado muda com o preço; vira realizado quando a posição é fechada.'],['Custos e liquidação','Taxas, funding, spread e slippage reduzem o resultado. Mark Price (usado na liquidação) e Index Price (referência entre bolsas) podem diferir do último preço. Liquidação é o fechamento forçado por margem insuficiente.']],q:['O que é margem?',['O lucro da operação','O capital separado como garantia da posição','A taxa da corretora'],1,'Valor da posição = margem × alavancagem.']},
{t:'2. Risco e alavancagem',a:[['Alavancagem e margem','Alavancagem aumenta a exposição, nunca garante lucro. Margem inicial abre a posição; margem de manutenção é o mínimo para mantê-la. Quanto maior a alavancagem, mais perto fica a liquidação.'],['Risco por operação','Risco = distância até o stop × tamanho da posição. Defina % máximo por operação e por dia. Drawdown é a queda desde o pico da banca; sequências de perdas acontecem, então o risco por operação deve ser pequeno.']],q:['Margem usada é o mesmo que risco da operação?',['Sim','Não: o risco é o que se perde até o stop','Só com 1x'],1,'Você pode usar pouca margem e arriscar muito, ou o contrário.']},
{t:'3. Leitura de gráficos',a:[['Candles','Cada candle mostra abertura, máxima, mínima e fechamento. Corpo grande indica força no período; pavio longo indica rejeição de preços. O timeframe é só o intervalo de cada candle, não a duração da operação.'],['Movimentos do preço','Tendência, consolidação, rompimento (preço passa de um nível), falso rompimento (volta logo) e pullback (recuo dentro da tendência).']],q:['Pavio longo em um candle costuma indicar:',['Rejeição de preço naquele nível','Reversão garantida','Erro de dados'],0,'Indica disputa, mas não garante o que vem depois.']},
{t:'4. Suporte e resistência',a:[['Zonas e reações','Suporte e resistência são regiões (não linhas exatas) onde o preço já reagiu. Quanto mais toques e reações, mais relevante a zona.'],['Rompimento e reteste','Após romper, o preço costuma retestar o nível: suporte rompido pode virar resistência e vice-versa. Nada disso é garantido.']],q:['Um suporte rompido pode passar a atuar como:',['Resistência','Volume','Funding'],0,'É a inversão de função, observada com frequência mas sem garantia.']},
{t:'5. Médias móveis',a:[['MM, SMA e EMA','Média móvel é o preço médio dos últimos N candles. SMA pesa todos igual; EMA dá mais peso aos recentes. MM20/25 são curtas, MM50 intermediária, MM99/200 longas.'],['Como interpretar','Observe inclinação, posição do preço (acima/abaixo) e alinhamento entre médias. Cruzamentos atrasam e geram sinais falsos, principalmente em mercado lateral. Nunca use como sinal isolado.']],q:['Cruzamento de médias é sinal garantido?',['Sim','Não, pode gerar sinais falsos','Só na EMA'],1,'Indicadores são ferramentas de análise, não garantias.']},
{t:'6. Volume',a:[['Leitura do volume','Volume é a quantidade negociada. Rompimento com volume acima da média mostra mais participação; sem volume, aumenta o risco de falso rompimento.'],['Preço e volume','Alta com volume caindo pode indicar perda de força; rejeição com volume alto mostra disputa forte. Compare sempre com o volume médio.']],q:['Rompimento com volume fraco tende a ser:',['Mais confiável','Mais suspeito','Irrelevante'],1,'Pouca participação aumenta a chance de falso rompimento.']},
{t:'7. Indicadores',a:[['RSI e MACD','RSI (0–100) mede a força recente: acima de 70 ou abaixo de 30 indica movimento esticado, não reversão automática. MACD compara EMAs e mostra momento e cruzamentos.'],['Bollinger, SAR e combinações','Bollinger mede volatilidade em torno de uma média; SAR sinaliza possível inversão e falha muito em lateral. Erro comum: usar um indicador só e ignorar a estrutura. Combine com níveis, estrutura e volume.']],q:['RSI acima de 70 significa venda obrigatória?',['Sim','Não, indica apenas força/esticamento','Só no 1 minuto'],1,'Em tendência forte o RSI pode ficar alto por muito tempo.']},
{t:'8. Estrutura de mercado',a:[['HH, HL, LH, LL','Alta: máximas e mínimas cada vez mais altas (HH/HL). Baixa: LH/LL. Lateralização: sem sequência clara.'],['Mudança de estrutura','Na alta, perder a última mínima (HL) sugere enfraquecimento e possível mudança de estrutura. Só se confirma com o desenrolar do preço.']],q:['HH e HL formam tendência de:',['Alta','Baixa','Lateralização'],0,'Máximas e mínimas ascendentes definem a alta.']},
{t:'9. Estratégias',a:[['Tendência, pullback e rompimento','Toda ideia precisa de contexto, entrada hipotética, stop, alvo, risco e o que a invalida. Tendência: seguir a direção. Pullback: entrada no recuo. Rompimento: passagem de nível com volume.'],['Reversão, S/R e confluência','Reversão exige sinais de rejeição e stop curto; S/R usa reação em zonas; confluência combina fatores independentes. Quando NÃO operar: lateral sem nível, sem stop, sem motivo objetivo.']],q:['Confluência significa:',['Vários fatores independentes apontando para o mesmo cenário','Garantia de lucro','Usar muitos indicadores iguais'],0,'Aumenta a qualidade da análise, não elimina o risco.']},
{t:'10. Psicologia e disciplina',a:[['Armadilhas emocionais','FOMO (entrar por medo de perder), revenge trading (tentar recuperar perda), overtrading, aumentar posição para recuperar, operar sem setup e quebrar stop levam a perdas maiores.'],['Disciplina','Siga um plano escrito, respeite stop e limites diários, registre no diário e revise. Não operar também é uma decisão válida.']],q:['Aumentar a posição para recuperar uma perda é:',['Boa prática','Armadilha comum','Obrigatório'],1,'Aumenta o risco justamente quando o julgamento está pior.']}];
const GLOS=[['Long','Posição que lucra com a alta do ativo.'],['Short','Posição que lucra com a queda do ativo.'],['Leverage (alavancagem)','Multiplicador da exposição sobre a margem.'],['Margin (margem)','Capital separado como garantia da posição.'],['Liquidation (liquidação)','Fechamento forçado quando a margem não sustenta a perda.'],['Funding','Pagamento periódico entre compradores e vendedores no perpétuo.'],['PnL','Lucro ou prejuízo da posição.'],['Stop Loss','Ordem que encerra a posição ao atingir um preço de perda planejada.'],['Take Profit','Ordem que encerra a posição ao atingir o alvo.'],['Entry','Preço de entrada da posição.'],['Position Size','Tamanho da posição, definido pelo risco e pela distância do stop.'],['Risk/Reward','Relação entre o risco assumido e o retorno potencial.'],['Drawdown','Queda da banca a partir de um pico.'],['Volume','Quantidade negociada em um período.'],['Volatility (volatilidade)','Intensidade das variações de preço.'],['Spread','Diferença entre o preço de compra e o de venda.'],['Slippage','Diferença entre o preço esperado e o executado.'],['Support (suporte)','Região onde o preço já encontrou compradores.'],['Resistance (resistência)','Região onde o preço já encontrou vendedores.'],['Trend (tendência)','Direção predominante do preço.'],['Pullback','Recuo temporário dentro de uma tendência.'],['Breakout (rompimento)','Preço ultrapassa um nível relevante.'],['Fakeout (falso rompimento)','Rompimento que não se sustenta e volta.'],['EMA','Média móvel exponencial: pesa mais os candles recentes.'],['SMA','Média móvel simples: todos os candles pesam igual.'],['RSI','Indicador de força relativa, de 0 a 100.'],['MACD','Indicador de momento baseado em EMAs.'],['Bollinger','Bandas de volatilidade em torno de uma média.'],['SAR','Parabolic SAR: pontos que acompanham a tendência e sugerem inversão.'],['Mark Price','Preço de referência usado para PnL não realizado e liquidação.'],['Index Price','Preço de referência médio de várias bolsas.']];
const QUIZ=[
['O que representa uma vela de 15 minutos?',['O intervalo de tempo de cada candle','O tempo que a operação deve durar','Um sinal de compra'],0,'O timeframe define apenas o intervalo de cada candle.'],
['A alavancagem aumenta apenas o potencial de ganho?',['Sim','Não, aumenta também o de perda','Só reduz taxas'],1,'Ela amplia a exposição, então amplia ganhos e perdas.'],
['O que é margem?',['O lucro da operação','O capital separado como garantia da posição','A taxa da corretora'],1,'Valor da posição = margem × alavancagem.'],
['O que acontece quando o preço chega ao stop?',['A posição é encerrada na ordem de stop (pode haver slippage)','O preço volta','Nada'],0,'O stop reduz risco, mas não o elimina.'],
['O que é funding?',['Pagamento periódico entre compradores e vendedores do perpétuo','Taxa de saque','Um indicador'],0,'Pode ser custo ou receita conforme o lado.'],
['O que é liquidação?',['Fechamento forçado por margem insuficiente','Take profit','Uma ordem limite'],0,'Ocorre quando a perda consome a margem de manutenção.']];
const CHECK=['Ativo definido','Timeframe principal definido','Tendência identificada','Suporte/resistência marcados','Topos e fundos analisados','Risco de falso rompimento avaliado','Médias móveis analisadas','Volume analisado','RSI/MACD analisados (se usa)','Analisei 4H','Analisei 1H','Analisei 15M','Analisei 5M'];
const TREINOS=[
{t:'Cenário 1 — Tendência de alta',ativo:'QNTUSDT',tf:'15m',d:[['Preço atual','102,00'],['Suporte','98,00'],['Resistência','108,00'],['Médias','Preço acima da MM20 e da MM50, ambas inclinadas para cima'],['Volume','Crescente nas últimas velas de alta'],['RSI','62'],['MACD','Positivo']],q:[
['Qual é a tendência?',['Alta','Baixa','Lateral'],0,'Preço acima de médias inclinadas para cima e volume acompanhando indicam estrutura de alta.'],
['Onde está o suporte mais próximo?',['98,00','108,00','102,00'],0,'O suporte fica abaixo do preço; a resistência, acima.'],
['Quais elementos confirmam o cenário de alta?',['Só o RSI','Médias, volume e MACD alinhados','Nenhum'],1,'Vários fatores independentes na mesma direção formam confluência.'],
['Onde estaria a invalidação da ideia de alta?',['Perda do suporte em 98,00','Rompimento de 108,00','RSI em 62'],0,'Perder o suporte enfraquece a estrutura de alta e a ideia deixa de valer.'],
['Com banca de US$ 1.000 e risco de 1%, qual é a perda máxima planejada?',['US$ 1','US$ 10','US$ 100'],1,'1% de 1.000 = US$ 10. O tamanho da posição sai desse valor dividido pela distância até o stop.']]},
{t:'Cenário 2 — Mercado lateral',ativo:'TESTUSDT',tf:'1h',d:[['Preço atual','50,20'],['Faixa','48,00 a 52,00, há várias horas'],['Médias','Planas e se cruzando várias vezes'],['Volume','Baixo e decrescente'],['RSI','50'],['MACD','Próximo de zero']],q:[
['Qual é o contexto?',['Tendência de alta','Lateralização','Tendência de baixa'],1,'Preço preso entre 48 e 52, com médias planas.'],
['Cruzamentos de médias aqui tendem a ser:',['Sinais confiáveis','Sinais falsos frequentes','Garantia de rompimento'],1,'Em mercado lateral, médias se cruzam sem que haja tendência.'],
['O que o volume baixo sugere?',['Pouca participação e risco de falso rompimento','Rompimento iminente garantido','Nada'],0,'Sem participação, movimentos tendem a não se sustentar.'],
['Qual conduta é mais coerente com o estudo?',['Entrar já para não perder','Esperar rompimento confirmado ou não operar','Aumentar a alavancagem'],1,'Sem direção clara, esperar ou não operar é uma decisão válida.'],
['Uma ideia de compra no suporte teria invalidação em:',['Fechamento abaixo de 48,00','Preço em 50,20','RSI em 50'],0,'Perder a faixa por baixo invalida a ideia de reação no suporte.']]},
{t:'Cenário 3 — Possível falso rompimento',ativo:'DEMOUSDT',tf:'5m',d:[['Resistência','210,00'],['Movimento','Máxima em 211,50 e retorno para 208,00'],['Candle','Pavio superior longo'],['Volume no rompimento','Abaixo da média'],['RSI','74'],['Preço atual','208,00']],q:[
['O que o movimento sugere?',['Possível falso rompimento','Tendência de alta confirmada','Suporte rompido'],0,'O preço passou da resistência e voltou, com pavio longo e pouco volume.'],
['Um pavio superior longo indica:',['Rejeição de preços mais altos','Força compradora garantida','Erro de dados'],0,'Mostra que os compradores não sustentaram o preço.'],
['RSI em 74 significa que se deve vender?',['Sim, obrigatoriamente','Não, indica esticamento, não sinal automático','Só em 5 minutos'],1,'RSI alto pode persistir em tendência forte; é contexto, não ordem.'],
['Entrar comprado por medo de perder o movimento seria:',['FOMO','Disciplina','Confluência'],0,'FOMO é entrar por emoção, sem plano e sem stop definido.'],
['O que faria sentido antes de qualquer plano?',['Esperar confirmação e definir stop e risco','Operar com alavancagem máxima','Ignorar o volume'],0,'Confirmação, stop e risco vêm antes da decisão.']]}];
const ESTRAT=[
['Tendência','Estrutura clara de HH/HL (ou LH/LL) com médias alinhadas.','Na continuação da direção, após confirmação.','Abaixo do último fundo (alta) ou acima do último topo (baixa).','Próxima zona de resistência/suporte ou múltiplo do risco.','Distância até o stop × tamanho da posição.','Perda da estrutura (último HL/LH).','Mercado lateral ou médias desalinhadas.'],
['Pullback','Tendência definida e recuo até média ou suporte.','Quando o recuo mostra rejeição e volta a favor da tendência.','Abaixo do fundo do recuo.','Retomada da máxima anterior ou zona acima.','Recuo pode virar mudança de estrutura.','Fechamento abaixo do fundo do recuo.','Recuo com volume forte contra a tendência.'],
['Rompimento','Preço comprimido junto a suporte/resistência relevante.','Após fechamento além do nível, idealmente com reteste.','Dentro da faixa anterior, além do nível rompido.','Altura da faixa projetada ou próxima zona.','Falso rompimento é comum com pouco volume.','Retorno para dentro da faixa.','Volume fraco ou movimento já exagerado.'],
['Reversão','Movimento esticado chegando a zona importante.','Só após sinal de rejeição (pavio, perda de força).','Logo além da extremidade da rejeição.','Primeiro nível relevante na direção oposta.','Contra a tendência: taxa de erro maior.','Novo extremo além do stop.','Sem rejeição visível ou sem zona clara.'],
['Suporte/Resistência','Zonas testadas várias vezes.','Reação confirmada na zona, com candle de rejeição.','Além da zona, com margem para ruído.','Zona oposta.','Zonas podem ser perdidas com força.','Fechamento firme além da zona.','Zona sem histórico ou preço no meio da faixa.'],
['Confluência','Vários fatores independentes (estrutura, nível, médias, volume) apontando no mesmo sentido.','Quando ao menos 3 fatores independentes concordam.','Conforme o fator de invalidação principal.','Próxima zona relevante.','Confluência melhora a qualidade, não elimina o risco.','Quebra do fator principal.','Fatores repetidos que medem a mesma coisa.']];
const INDIC=[
['RSI','Índice de força relativa: oscila de 0 a 100 comparando altas e baixas recentes.','Medir força e esticamento do movimento.','Acima de 70: esticado para cima; abaixo de 30: esticado para baixo; 50 separa força de fraqueza. Em tendência forte pode ficar em extremos por muito tempo.','Vender só porque passou de 70; ignorar a tendência.','Com estrutura, suporte/resistência e volume.','RSI 74 após candle de pavio longo em uma resistência: ponto de atenção, não venda automática.'],
['MACD','Compara duas EMAs (12 e 26) e uma linha de sinal (9).','Mostrar momento e mudanças de força.','Linha acima da sinal e histograma crescendo: momento positivo; o inverso, negativo. Os cruzamentos chegam com atraso.','Operar todo cruzamento em mercado lateral.','Com tendência, níveis e volume.','MACD cruza para cima com preço acima da MM50: momento a favor da alta, mas ainda exige stop e plano.'],
['Bollinger Bands','Média (normalmente 20) com bandas a 2 desvios-padrão.','Medir volatilidade e a posição relativa do preço.','Bandas apertadas indicam baixa volatilidade e possível expansão; preço colado na banda não é reversão automática.','Vender sempre que toca a banda superior.','Com estrutura e volume.','Bandas apertadas antes de um rompimento: aguarde direção e confirmação.'],
['SAR','Parabolic SAR: pontos acima ou abaixo do preço que acompanham a tendência.','Sugerir ajuste de stop (trailing) e possíveis inversões.','Pontos abaixo do preço indicam pressão de alta; acima, de baixa. A inversão dos pontos é aviso, não ordem.','Usar em mercado lateral, onde ele inverte demais.','Só com tendência definida por estrutura e médias.','Pontos subindo abaixo do preço podem ajudar a decidir onde subir o stop.'],
['Volume','Quantidade negociada em cada candle.','Avaliar participação e convicção do movimento.','Volume acima da média em rompimento reforça o movimento; volume caindo em alta sugere perda de força.','Olhar o volume sem compará-lo com a média.','Com rompimentos, rejeições e suporte/resistência.','Rompimento de resistência com volume abaixo da média: maior risco de falso rompimento.'],
['Médias móveis','Preço médio dos últimos N candles (SMA simples ou EMA exponencial).','Visualizar direção e servir de referência dinâmica.','Observe inclinação, posição do preço e alinhamento (ex.: MM20 acima da MM50).','Tratar cruzamento como sinal garantido.','Com estrutura e volume.','Preço acima da MM50 inclinada para cima: contexto favorável à alta, sem garantia.'],
['ATR','Average True Range: média da amplitude dos candles.','Medir volatilidade em unidades de preço.','ATR alto: movimentos amplos, exigem stop maior e posição menor; ATR baixo: movimentos curtos.','Usar stop menor que o ruído normal do ativo.','Com o risco por operação, para dimensionar a posição.','ATR de 2,0 e stop a 1,5×ATR = 3,0 de distância; posição = risco ÷ 3,0.']];
