const MODULOS=[
{t:'1. Fundamentos',b:['Trading é comprar e vender ativos tentando lucrar com variações de preço. Mercado futuro negocia contratos cujo preço deriva de um ativo. Contrato perpétuo não tem vencimento. Long lucra com alta; Short lucra com queda (antes de custos).','Exemplo: entrada 100, saída 105. Long: +5%. Short: −5%. À vista você compra o ativo; em futuros você negocia um contrato sobre ele.']},
{t:'2. Margem e alavancagem',b:['Margem é o capital que você separa. Valor da posição = margem × alavancagem. Exemplo: US$ 20 × 10x = US$ 200 de posição. Alavancagem não multiplica seu dinheiro: multiplica a exposição, tanto do ganho quanto da perda.','Com 10x, uma queda de ~10% contra você pode consumir toda a margem (liquidação). Use a calculadora de alavancagem para ver.']},
{t:'3. Long e Short',b:['Long: você se beneficia da alta. Short: da queda. Ambos antes de taxas e outros custos.','Entrada 100 → saída 105: Long +5%, Short −5%. Entrada 100 → saída 95: Short +5%, Long −5%. Com 10x sobre a margem, os percentuais sobre a margem são multiplicados por 10.']},
{t:'4. Custos',b:['Taxa de entrada e de saída, funding (pagamento periódico entre compradores e vendedores do perpétuo), spread (diferença compra/venda) e slippage (diferença entre preço esperado e executado).','Valores reais dependem da corretora, do contrato e do momento. Use a Calculadora de Futuros para estimar.']},
{t:'5. Gestão de risco',b:['Arriscar um percentual pequeno da banca por operação. Tamanho da posição = risco em dinheiro ÷ distância até o stop. Margem usada não é o risco efetivo: o risco é o que você perde se o stop for atingido.','Defina limite diário de perda. Stop não elimina todos os riscos (gaps e slippage podem executar pior).']},
{t:'6. Leitura de gráficos',b:['Candle: abertura, máxima, mínima, fechamento. Verde/vermelho indica fechamento acima/abaixo da abertura. Corpo = abertura→fechamento; pavios = extremos.','Timeframe (1m, 5m, 15m, 1h, 4h, 12h, 1d) é o intervalo de cada candle. Uma vela de 4 horas não significa que a operação dura 4 horas: ela termina quando você fecha ou por stop, take profit ou liquidação.']},
{t:'7. Tendência',b:['Alta: topos e fundos mais altos. Baixa: mais baixos. Consolidação: preço lateral. Suporte e resistência são regiões onde o preço já reagiu. Rompimentos podem ser falsos.','Exemplo: preço faz fundos em 90, 95, 100 → estrutura de alta até perder o último fundo.']},
{t:'8. Médias móveis',b:['SMA é a média simples dos últimos N candles; EMA dá mais peso aos recentes. MA10 no gráfico de 15 min = média dos últimos 10 candles de 15 min.','Cruzamentos não são sinal garantido: indicadores são ferramentas e geram sinais falsos.']},
{t:'9. Indicadores',b:['RSI: mede força/velocidade (0–100); limites 30/70 não são sinais automáticos. MACD: relação entre duas EMAs, mostra momento. Bollinger: bandas de volatilidade em torno de uma média. Volume: confirma ou enfraquece movimentos. ATR: volatilidade média, útil para dimensionar stops.','Erros comuns: usar um só indicador, ignorar a estrutura, procurar combinação mágica.']},
{t:'10. Multi-timeframe',b:['Metodologia didática (não regra universal): 4H contexto, 1H tendência intermediária, 15M estrutura da operação, 5M refinamento da entrada.','Marque no checklist os períodos que você analisou.']}];
const QUIZ=[
['O que representa uma vela de 15 minutos?',['O intervalo de tempo de cada candle','O tempo que a operação deve durar','Um sinal de compra'],0,'O timeframe define apenas o intervalo de cada candle.'],
['A alavancagem aumenta apenas o potencial de ganho?',['Sim','Não, aumenta também o de perda','Só reduz taxas'],1,'Ela amplia a exposição, então amplia ganhos e perdas.'],
['O que é margem?',['O lucro da operação','O capital separado como garantia da posição','A taxa da corretora'],1,'Valor da posição = margem × alavancagem.'],
['O que acontece quando o preço chega ao stop?',['A posição é encerrada na ordem de stop (pode haver slippage)','O preço volta','Nada'],0,'O stop reduz risco, mas não o elimina.'],
['O que é funding?',['Pagamento periódico entre compradores e vendedores do perpétuo','Taxa de saque','Um indicador'],0,'Pode ser custo ou receita conforme o lado.'],
['O que é liquidação?',['Fechamento forçado por margem insuficiente','Take profit','Uma ordem limite'],0,'Ocorre quando a perda consome a margem de manutenção.']];
const CHECK=['Ativo definido','Timeframe principal definido','Tendência identificada','Suporte/resistência marcados','Topos e fundos analisados','Risco de falso rompimento avaliado','Médias móveis analisadas','Volume analisado','RSI/MACD analisados (se usa)','Analisei 4H','Analisei 1H','Analisei 15M','Analisei 5M'];
